### ISSUE TITLE
Environment deployment dependencies

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1112]
Currently, all environment deployments within the build run simultaneously. However, sometimes they have to be run in particular order. This is especially important for Deployment Agent environments as they cannot be "inline".

The idea is to add "depends_on" setting to the environment deployment, so for example to deploy to 3 servers consequently we would have:

```yaml
deploy:

- provider: Environment
  name: Server1

- provider: Environment
  name: Server2
  depends_on: Server1

- provider: Environment
  name: Server3
  depends_on: Server2
```
