### ISSUE TITLE
'Serilog' already has a dependency defined for 'Microsoft.CSharp'.

### ISSUE THREAD

**Issue by jeff-pang** [appveyor/ci#1132]
I am encountering this error on AppVeyor Build. Based on stackoverflow, the solution is to update nuget (but the q&a was back in 2014/15). What should I do to resolve this?

[Stack Overflow Answer](http://stackoverflow.com/questions/25725545/nuget-x-already-has-a-dependency-defined-for-y)

**Comment by IlyaFinkelshteyn** [comment]
Hi Jeff,

Can you  please try to call `nuget restore <path_to_your_project>` at install stage in AppVeyor build and let us know the results?

--ilya.

**Comment by jeff-pang** [comment]
@IlyaFinkelshteyn I am still getting `'Serilog' already has a dependency defined for 'Microsoft.CSharp'` after I have tried using the following variations of nuget restore in the install stage:

- nuget restore
- nuget restore `path to sln`
- nuget restore `path to packages.config`

**Comment by IlyaFinkelshteyn** [comment]
Can you please try to install latest nuget at `install` stage:

```
- ps: if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
- ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe', "$nugetDir\NuGet.exe")
```

--ilya.

**Comment by jeff-pang** [comment]
@IlyaFinkelshteyn still getting the same error after adding the script. 

I have done 2 variations of as follows:

```
install:
 - ps: if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
 - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe', "$nugetDir\NuGet.exe")
 - nuget restore
```

```
install:
 - ps: if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
 - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe', "$nugetDir\NuGet.exe")

before_build:
 - nuget restore
```


If you wish, I can provide you with access to the project so that you can have a better look at how the project is set up.
