### ISSUE TITLE
Environment variables do not get expanded recursively

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#1134]
I have this in `appveyor.yml`:

```
environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)
  GOPATH: $(HOME)\go
  PATH: $(PATH);$(GOPATH)\bin;C:\Python27\Scripts;$(HOME)\rebar
```

which gets [expanded to](https://ci.appveyor.com/project/sschuberth/licensefinder/build/1.0.18)

```
...;$(HOME)\go\bin;C:\Python27\Scripts;C:\Users\appveyor\rebar
```

i.e. `$(GOPATH)` gets expanded to `$(HOME)\go`, but `$(HOME)` does not get expanded further. Note how `$(HOME)` _does_ get expanded for `$(HOME)\rebar`.
