### ISSUE TITLE
How to install a compiler (32-bit installer) and run that 32-bit compiler on AppVeyor?

### ISSUE THREAD

**Issue by Paebbels** [appveyor/ci#1144]
Hello,

I would like to compile an Ada program on your CI platform. And after that run a little test suite.
The compiler is [GNAT GPL 2016 (Win32)](http://libre.adacore.com/download/). The compiler's installer was built with NSIS and is a 32-bit executable.

**Error message from AppVeyor:**
> Program 'gnat-gpl-2016-x86-windows-bin.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1

**Your machines are configured as follows, regarding Data Execution Prevention (DEP):**
> DataExecutionPrevention_32BitApplications : True
> DataExecutionPrevention_Available         : True
> DataExecutionPrevention_Drivers           : True
> DataExecutionPrevention_SupportPolicy     : 3

Why is `DataExecutionPrevention_SupportPolicy` set to 3 (OptOut) instead to 2 (OptIn - default)?
This disables all external 32-bit applications on you machines!

Kind regards
    Patrick Lehmann

**Further reading:**
* https://support.microsoft.com/en-us/kb/912923

**Comment by FeodorFitsner** [comment]
You can change DEP policy and restart worker VM. Try the following:

```yaml
install:
- bcdedit /set {current} nx AlwaysOff
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 5
```

**Comment by Paebbels** [comment]
Hello Deodor,

I didn't know I can restart "my" instance and get the same instance back with changed settings.
What is the maximum runtime of a AppVeyor job?
Other CI systems have a hard boundary of e.g. 45 minutes.
Do both runs count in the same session?

I don't want to undermine your VM security by restarting the VMs.
When is the CI result emitted to e.g. GitHub?
Does the restart cause a build error to be displayed?

I'll try to write a startup switch
* if policy == 3 -> bcdedit + reboot
* else run my scripts

Thanks so far
    Patrick

**Comment by FeodorFitsner** [comment]
maximum run time is 60 minutes - no matter how many times VM is restarted. You are not undermining the security of VM - it will be re-created when the build is over. Every time you get a new random VM from a pool - it's not the same machine.

**Comment by Paebbels** [comment]
Ohoh,

I think I created a endless loop:

![image](https://cloud.githubusercontent.com/assets/956109/19875541/cb078d0e-9fcd-11e6-8ba6-1b20554410b5.png)

The first execution gives this log:
![image](https://cloud.githubusercontent.com/assets/956109/19875564/ff64988a-9fcd-11e6-8696-6a8f1428eac5.png)

This is my Script (after I fixed the typo):
```PowerShell
Write-Host "========================================" -Foreground Yellow
Write-Host "   Running AppVeyor.GNAT.install.ps1    " -Foreground Yellow
Write-Host "========================================" -Foreground Yellow
Write-Host "Testing for Data Execution Prevention (DEP) Policy setting..."
$cim = Get-CimInstance Win32_OperatingSystem

if ($cim.DataExecutionPrevention_SupportPolicy -eq 3)
{	Write-Host "Data Execution Prevention (DEP) is enabled. Rebooting ..."
	Write-Host "  Disabling DEP via bcdedit"
	bcdedit /set {current} nx AlwaysOff
	Write-Host "  Rebooting ..." -Foreground Yellow
	Restart-Computer -Force
	Start-Sleep -s 5
}
else
{	Write-Host "Data Execution Prevention is disabled."
	Write-Host "  Installing GNAT GPL 2016..." -Foreground Yellow
	Write-Host "  List Git-LFS files"
	Write-Host "  ----------------------------------------"
	git lfs ls-files
	Write-Host "  ----------------------------------------"
	$SilentInstallJob = Start-Job {
		Set-Location $args[0]
		Invoke-Expression ".\dist\git-lfs\gnat-gpl-2016-x86-windows-bin.exe /S"
	} -ArgumentList (Get-Location)
	Wait-Job $SilentInstallJob
	Receive-Job $SilentInstallJob
	Write-Host "----------------------------------------"

	# git lfs install
	git lfs pull
	Write-Host "----------------------------------------"

	dir "c:\gnatpro"
}
```

**Comment by IlyaFinkelshteyn** [comment]
Hi Patrick,

I believe that problem is that Appveyor treats this script as a single atomic step and therefore considers it as done and do not re-run it after reboot.

What I recommend to do is spread this logic between different stages and make things more straightforward. Try this in `appveyor.yml`:

```
version: 0.34-dev-{build}
clone_folder: c:\projects\ghdl
init:
  - ps: Set-ExecutionPolicy Unrestricted -Force
  - ps: Write-Host "  Disabling DEP via bcdedit"
  - ps: bcdedit /set {current} nx AlwaysOff
  - ps: Write-Host "  Rebooting ..." -Foreground Yellow
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 5

install:
  - ps: Write-Host "  Installing GNAT GPL 2016..." -Foreground Yellow
  - ps: Write-Host "  List Git-LFS files"
  - ps: Write-Host "  ----------------------------------------"
  - ps: git lfs ls-files
  - ps: Write-Host "  ----------------------------------------"
  - ps: $SilentInstallJob = Start-Job {Set-Location $args[0]; Invoke-Expression ".\dist\git-lfs\gnat-gpl-2016-x86-windows-bin.exe /S"} -ArgumentList (Get-Location)
  - ps: Wait-Job $SilentInstallJob
  - ps: Receive-Job $SilentInstallJob
  - ps: Write-Host "----------------------------------------"
  - ps: git lfs pull
  - ps: Write-Host "----------------------------------------"
  - ps: dir "c:\gnatpro"
```

Note the following:
- I removed `if-else` for simplicity at least for now.
- I separated Disabling DEP to `init` stage.
- I added sleep before reboot to give messages time to appear in console, otherwise they can be lost.
- I moved logic from `else` part to `install` stage because it seems more suitable. But sure you can run it as part of `before_build` too.
- I removed scripts and also decide not to do [multi-line code blocks](https://www.appveyor.com/docs/build-configuration/#script-blocks-in-build-configuration), because flat commands sequence is easiest to debug. But you can use scripts or code blocks if you prefer.
- I am not sure .but I think that you will end up with this error about project or solution file after successful `install` step with this `appveyor.yml` too. This is because by default AppVeyor is trying to find Visual Studio project or solution file and run msbuild against it, which is not your case as I understand. Per my understanding you also need to add your custom build command to `build_script` section.

--ilya.

**Comment by Paebbels** [comment]
Hello,

I tried your example code. I needed to remove `{current}` from the bcdedit command line. I don't know why, because every website describes the command as you wrote it in your answer ...

**What are my observations?**

Multiple runs are queued in your system. The first line was shown after the second line reached the reboot command:
![image](https://cloud.githubusercontent.com/assets/956109/19894634/fdfad060-a04d-11e6-87ed-1f4216418623.png)

Right now, I see 4 runs for the same commit hash, each of circa 1:30 minutes:
![image](https://cloud.githubusercontent.com/assets/956109/19894728/58344f34-a04e-11e6-80ee-4d1bba5b1ddd.png)

As these experiments show, the reboot needs to be conditional, otherwise it will issue reboot commands even if the DEP policy value is good for my use case. So I made the reboot conditional, based on the DEP policy value.

**As far as I can see, I get a new fresh VM after each reboot. I don't get the same VM with altered boot settings.**

Every run shows, that DEP is set to 3:
* https://ci.appveyor.com/project/Paebbels/ghdl/build/0.34-dev-20
* https://ci.appveyor.com/project/Paebbels/ghdl/build/0.34-dev-21
* https://ci.appveyor.com/project/Paebbels/ghdl/build/0.34-dev-22
* https://ci.appveyor.com/project/Paebbels/ghdl/build/0.34-dev-23
* https://ci.appveyor.com/project/Paebbels/ghdl/build/0.34-dev-24

What should I change?

**Comment by IlyaFinkelshteyn** [comment]
Below is YAML content I used to show how it should work. I believe it is self-explained with comments

[Build with this YAML](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/1.0.87) - also I believe self-explainable.  


```
version: 1.0.{build}

init:
  # Checking that DEP ss enabled
  - ps: $cim = Get-CimInstance Win32_OperatingSystem
  - ps: $depEnabled = $cim.DataExecutionPrevention_SupportPolicy -eq 3
  - ps: Write-Host "DEP is enabled? $depEnabled"
  - ps: Set-ExecutionPolicy Unrestricted -Force
  - ps: Write-Host "  Disabling DEP via bcdedit"
  
  # Disabling DEP -- note that I use CMD, not PowerShell for {} to be treated as correctly
  - cmd: bcdedit /set {current} nx AlwaysOff
  
  # here we create marker folder to proof that VM will not be changed
  - ps: $markerFolderExists = Test-Path c:\myfolder123
  - ps: Write-Host "Narker folder exists? $markerFolderExists"
  - ps: Write-Host "Creating marker folder"
  - ps: New-Item -Path c:\myfolder123 -ItemType Directory
  
  - ps: Write-Host "  Rebooting ..." -Foreground Yellow
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 5

install:
  - ps: Write-Host "Install stage after reboot"   
  
  # Checking that now DEP is disabled
  - ps: $cim = Get-CimInstance Win32_OperatingSystem
  - ps: $depEnabled = $cim.DataExecutionPrevention_SupportPolicy -eq 3
  - ps: Write-Host "DEP is enabled? $depEnabled"
  
  # Ensurig that it is indeed the same VM
  - ps: Write-Host "Testing that marker folder exist to ensure that it is the same VM"
  - ps: $sameVm = Test-Path c:\myfolder123
  - ps: Write-Host "Same VM? $sameVm"
  
build: off
```

What about multiple builds, please check that you don't have multiple identical webhooks which start AppVeyor build in your GitLab settings.

--ilya.
