### ISSUE TITLE
Cannot delete a file from site-package

### ISSUE THREAD

**Issue by ShyPixie** [appveyor/ci#1171]
I'm using the function bellow for delete a conflicting file from gevent module (my setup don't work with this file present). 

```
def fix_gevent():
    for site_ in site.getsitepackages():
        full_path = os.path.join(site_, 'gevent')
        if os.path.isdir(full_path):
            for file_ in os.listdir(full_path):
                if file_ == '_util_py2.py':
                    os.remove(os.path.join(full_path, file_))
```

But this function doesn't work with appveyor, because the real path for the gevent module is at "C:\Users\appveyor\AppData\Roaming\Python\Python34\site-packages\gevent\", and it's not listed in the python site.

I don't understand. The appveyor python is not installed at C:\Python*? It makes no sense. And how python is getting package from there if it's not listed as a site-package dir?

here is my yml:

```
environment:
    global:
        PYTHON32: 'C:\Python34'
        PYTHON64: 'C:\Python34-x64'
        PYTHON_VERSION: 3.4.4

clone_depth: 1
      
install:
    - call "%PYTHON32%\python.exe" -m pip install --user --disable-pip-version-check --upgrade pip
    - call "%PYTHON32%\python.exe" -m pip install --user py2exe
    - call "%PYTHON32%\python.exe" -m pip install --user requests
    - call "%PYTHON32%\python.exe" -m pip install --user beautifulsoup4
    - call "%PYTHON32%\python.exe" -m pip install --user psutil
    - call "%PYTHON32%\python.exe" -m pip install --user gevent

    - call "%PYTHON64%\python.exe" -m pip install --user --disable-pip-version-check --upgrade pip
    - call "%PYTHON64%\python.exe" -m pip install --user py2exe
    - call "%PYTHON64%\python.exe" -m pip install --user requests
    - call "%PYTHON64%\python.exe" -m pip install --user beautifulsoup4
    - call "%PYTHON64%\python.exe" -m pip install --user psutil
    - call "%PYTHON64%\python.exe" -m pip install --user gevent

build_script:
    - call %PYTHON64%\python.exe -u ./release.py"

artifacts:
    - path: 'release\*'
```
