### ISSUE TITLE
Cygwin chmod error

### ISSUE THREAD

**Issue by NiklasRosenstein** [appveyor/ci#1210]
I'm trying to use Cygwin on AppVeyor,  but I get an error when using `chmod`.

```
Build started
git clone -q --branch=appveyor-cygwin https://github.com/NiklasRosenstein/cpp-nr.git C:\projects\cpp-nr
git checkout -qf 74348e63a6636e5b551f5ced541cb32762b0d0cf
Running Install scripts
call %SCRIPT%
Collecting wget
  Downloading wget-3.2.zip
Installing collected packages: wget
  Running setup.py install for wget: started
    Running setup.py install for wget: finished with status 'done'
Successfully installed wget-3.2
Saved under apt-cyg
   1148 [main] chmod (2780) C:\Program Files\Git\usr\bin\chmod.exe: *** fatal error - cygheap base mismatch detected - 0x18033E408/0x180330400.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command exited with code 127
```

My appveyor.yml looks like this:

```yaml
build: off  # disable msbuild

environment:
  matrix:
    - SCRIPT: C:\cygwin64\bin\bash.exe .appveyor/cygwin-compile.sh
    - SCRIPT: .appveyor/msvc-compile.bat
      VSVERSION: 140

install:
  - call %SCRIPT%
```

And this is the Cygwin script:

```sh
#!/bin/bash
set -e

pip install wget

# Install apt-cyg
python -m wget https://raw.github.com/transcode-open/apt-cyg/master/apt-cyg
chmod +x apt-cyg
mv apt-cyg /usr/local/bin

# Install python3
apt-cyg python3 python3-virtualenv python3-pip
```
