### ISSUE TITLE
Substitute environment variables for deploy/on/variable setting 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1217]
In scenario like this:

```
deploy:
- provider: ABC
  ...
  on:
    APPVEYOR_REPO_BRANCH: $(MyVar)
``` 
`$(MyVar)` is not being resolved/substituted with variable value
