### ISSUE TITLE
Appveyor loses the first 2 or 3 log messages after a reboot

### ISSUE THREAD

**Issue by glennsarti** [appveyor/ci#1221]
I'm currently changing the local code page and then rebooting an Appveyor worker, however I found that coming out the reboot, I was dropping the first 2 or 3 log messages.  e.g.

appveyor.yml snippet (Setting to ja-JP locale)
``` yaml
before_test:
  - ps: >-
...
          Write-Output "Setting Locale to $testLocale ...";
          Set-WinSystemLocale ($testLocale);
          Write-Output "Restarting worker in 5 seconds...";
          Start-Sleep -Seconds 5
          Restart-Computer -Force -Confirm:$false;
...
test_script:
  - REM Starting in 4
  - REM Starting in 3
  - REM Starting in 2
  - REM Starting in 1
  - SET
  - chcp
  - ps: Get-WinSystemLocale
...
```

Yields the following log message output:

```
...
Setting Locale to ja-JP ...
Restarting worker in 5 seconds...
REM Starting in 2
REM Starting in 1
SET
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\appveyor\AppData\Roaming
APPVEYOR=True
APPVEYOR_ACCOUNT_NAME=puppetlabs
APPVEYOR_API_URL=http://localhost:1032/
...
```

Sometimes it will capture:
```
...
Setting Locale to ja-JP ...
Restarting worker in 5 seconds...
REM Starting in 3
REM Starting in 2
REM Starting in 1
```

I tried adding in a delay after the reboot (Start-Sleep) with no change.  It's as if the logging system needs a "jump start" after rebooting to start it see the log messages.
