### ISSUE TITLE
Android SDK Platform 24 License Agreements not accepted

### ISSUE THREAD

**Issue by purplecabbage** [appveyor/ci#1223]
My Apache Cordova + Android build is failing because it uses Android SDK 24 and the license agreement appears to need someone to actually click a button to accept it before it can be used.

```
File C:\Users\appveyor\.android\repositories.cfg could not be loaded.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 24].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

Full error log here:
https://ci.appveyor.com/project/purplecabbage/phonegap-plugin-multiview/build/1.0.14

**Comment by IlyaFinkelshteyn** [comment]
Please take a look at [this configuration](https://github.com/StoDevX/AAO-React-Native/blob/master/appveyor.yml). I did not test it but it seems @hawkrives made it work.

--ilya.

**Comment by hawkrives** [comment]
Yeah, it works for us.

First off, I download the android sdk manually:

```yaml
clone_folder: c:\projects\my-project
init:
  - cd \
  - appveyor DownloadFile "http://dl.google.com/android/android-sdk_r24.4.1-windows.zip"
  - 7z x "android-sdk_r24.4.1-windows.zip" > nul
  - cd c:\projects\my-project
```

That leaves the sdk in `C:\android-sdk-windows`.

I then invoke the command-line `android.bat` tool manually to install the items I want – it appears that you can specify multiple items to be installed at once by joining them with commas.

It still wants you to accept the license agreements, but since all of these items use the same Google license, it only asks once. We just pass it the 'y' character, so it continues on automatically.

`echo y | "C:\android-sdk-windows\tools\android.bat" --silent update sdk --no-ui --all --filter android-24,platform-tools,tools,build-tools-24.0.0`

Adjust `android-24` and `build-tools-24.0.0` as needed for your configuration.

---

For yours, I might try the following:

```yaml
# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_folder: c:\projects\my-project
init:
  - cd \
  - appveyor DownloadFile "http://dl.google.com/android/android-sdk_r24.4.1-windows.zip"
  - 7z x "android-sdk_r24.4.1-windows.zip" > nul
  - cd c:\projects\my-project

environment:
  matrix:
  - nodejs_version: "6"

install:
  - echo y | "C:\android-sdk-windows\tools\android.bat" --silent update sdk --no-ui --all --filter android-24,platform-tools,tools,build-tools-24.0.0
  - ps: Install-Product node $env:nodejs_version
  - netsh advfirewall firewall add rule name="Open Port 8008" dir=in action=allow protocol=TCP localport=8008
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g apache/cordova-paramedic
  - npm install -g cordova

build: off

test_script:
  - node --version
  - npm --version
  - msbuild /version
  - cordova --version
  - npm install
  - npm test
  - cordova-paramedic --platform android --plugin .
```

adjusting `android-24` and `build-tools-24.0.0` as needed.

---

I'm not sure where your config actually installs the android build tools, which is why I did it manually at the beginning.
