### ISSUE TITLE
fast_finish with allow_failure should not mark build as cancelled

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1231]
Sample build: https://ci.appveyor.com/project/ljharb/node-resolve-0clfj/build/1.0.12
appveyor.yml: https://github.com/ljharb/node-resolve/commit/7e78da28b2f3da0dff249384f239fd4b791ff5fd

**Comment by mloskot** [comment]
I think I'm hitting the same issue in Boost.GIL project.

The [.appveyor.yml](https://github.com/boostorg/gil/blob/762af55d0894e3571c85e6f1ea02256b21f125e2/.appveyor.yml#L44-L46) specifies both, `fast_finish: true` and `allow_failures:`.

Interestingly, it used to work but around 3 weeks ago, it stopped working and all build jobs following a failing job (which is allowed to fail), are being cancelled:

- build `1.0.594` shows it used to work: https://ci.appveyor.com/project/stefanseefeld/gil/builds/21035372
- build `1.0.595` shows it stopped working: https://ci.appveyor.com/project/stefanseefeld/gil/builds/21038342

/cc @stefanseefeld

-----

By the way, I wonder if the structure of `matrix`-es may affect how the build works. That is, the `environment.matrix` with all jobs and then `matrix` with copy of the jobs that we intend to allow failures for. Perhaps those two `matrix`-es should be merged somehow.

```
environment:
  matrix:
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      VARIANT: debug
      TEST_HEADERS: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      VARIANT: release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86
      VARIANT: debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86
      VARIANT: release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      VARIANT: debug
      GENERATOR: "Visual Studio 15 2017 Win64"
      CMAKE_CONFIG: Debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: true
  allow_failures:
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      VARIANT: release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      VARIANT: debug
      GENERATOR: "Visual Studio 15 2017 Win64"
      CMAKE_CONFIG: Debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
```
