### ISSUE TITLE
Random powershell error (concurrent pipelines)

### ISSUE THREAD

**Issue by a-teammate** [appveyor/ci#1247]
An error appears before even cloning the repo:
`The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.`

The error caused the job to fail.

See:
https://ci.appveyor.com/project/inexor-game/code/build/0.1509/job/ofysdwd0u7fmmaj7#L9
> Build started
> cmake --version
> Build started
> msbuild /version
> cmake version 3.7.1
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 14.0.25420.1The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.
> git clone -q --depth=1 --branch=master https://github.com/inexor-game/code.git C:\projects\inexor-game

The relevant bit of our [appveyor.yml](https://github.com/inexor-game/code/blob/master/appveyor.yml)
```yaml
version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 2

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version
```
