### ISSUE TITLE
Build history messages stuck as "Pending..."

### ISSUE THREAD

**Issue by docrinehart** [appveyor/ci#1306]
Not sure if this is related to running against the VS2017 RC build worker, but sometime the build seems to hang when getting started, and when this happens the build takes awhile on the clock and the message is left as "Pending..." even after the build succeeds.

![screenshot](https://cloud.githubusercontent.com/assets/5891405/22764227/ef094e9a-ee2e-11e6-94ef-0b0d15b6e3f9.png)

**Comment by FeodorFitsner** [comment]
Can you drop a link to a project/build please?

**Comment by docrinehart** [comment]
https://ci.appveyor.com/project/Headspring/serenityhr

**Comment by FeodorFitsner** [comment]
That repository is configured as "generic" Git repo. Whenever a new build is triggered by a webhook it doesn't contain the information about the commit, so AppVeyor puts "Pending..." and then tries to get commit details during the build using `git log` command. For some reason it fails to fetch commit info from log.

If it's GitHub or BitBucket repo you should configure it as "GitHub" or "BitBucket" project to get all the "benefits" such as automatic webhooks and PRs (GH only).

**Comment by docrinehart** [comment]
I tried to, but it wasn't showing up in the list of BitBucket projects. 

Also, I'm having some problems getting the node version to adjust to latest. (7.5.0) I've tried Install-Product and Update-NodeJsInstallation but the output from the build script keeps saying it's using node 4.x. I can open another issue for this if needed. Maybe I'm just doing something wrong?

**Comment by FeodorFitsner** [comment]
For AppVeyor to display BitBucket repo on "New project" page authorized user must be "Administrator" on that repo; otherwise the repo is getting filtered.

We've just updated Node.js to the latest. Modified `appveyor.yml` to install the latest 7.x:

```yaml
version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017 RC

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache

# Test against the latest version of this Node.js version
environment:
  nodejs_version: 7

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

build_script:
  - cmd: build ci
test: off
```
