### ISSUE TITLE
Add variable support in 'build.project' setting

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#131]
[Here is the convo](http://help.appveyor.com/discussions/problems/1446-yml-file-isnt-finding-my-solution-file). 

mainly this bit:

>Because nuget restore %solutionFile% is just a shell command while syntax $(something) in other parts is processed by build agent.
>
>I agree adding variables support to "project" would be really nice.

Then we could do tricky things like:

```
build:
  project: $(solutionFile)
  parallel: true
  verbosity: minimal
```

Yay!
