### ISSUE TITLE
Provide a tool to edit system / user environment PATH variable

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#1333]
In order to override system-wide programming language versions like Go 1.7.1 in `C:\do\bin` it would be nice to have a command line tool (e.g. as part of the `appveyor` tool, or a separate tool like `refreshenv`) that allows to remove (and add) individual paths from / to the PATH environment variable. The tool should directly edit the registry and be able to select between the system and user scope. That way one could easly override system Go 1.7.1 with a custom Go 1.8 by writing

    editpathenv system remove C:\go\bin
    editpathenv user add C:\tools\go\bin
    refreshenv

**Comment by FeodorFitsner** [comment]
I believe you don't need to change the registry, but you can change the current variable with a simple command like:

    set PATH=C:\<new-path-to-go>;%PATH%

**Comment by sschuberth** [comment]
Sure, but `set` is not persistent across different shell invocations. I.e. if you `set` something in `build_script:` it's not available in `test_script:`. Using `setx` would be persistent, but it [truncated to 1024 characters](http://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx).

Anyway, it just came to my mind that I could simply use the `environment:` section in my case. I'll check that.

**Comment by sschuberth** [comment]
Turns out using something like

    environment:
      PATH: c:\tools\go\bin;$(PATH)

works just fine, so I'm closing this. Thanks!

**Comment by jayvdb** [comment]
There are lots of existing tools for this, and would be good if one was added to the default image.

https://github.com/cmdf/extra-env is a very helpful tool.

I am using the following.

```yaml
environment:
  global:
    EXTRA_BIN: C:\tools\extra\bin
    EENV: $(EXTRA_BIN)\eenv.exe
    PATH: $(PATH);%EXTRA_BIN%;C:\tools\R\bin;C:\msys64\usr\bin;

script:
  # Persist the PATH set by AppVeyor so it is reloaded by refreshenv
  - if not exist %EENV% mkdir %EXTRA_BIN% & curl -fsSL -o %EENV%
        https://github.com/cmdf/extra-env/releases/download/1.0.0/eenv.exe
  - eenv.exe -m set PATH "%PATH%"
```

Next I want to find a sane replacement for RefreshEnv.cmd written in a real language ;-)  https://github.com/tischda/refresh looks good for that.

**Comment by Kristinita** [comment]
**Type: Problem** 😔

### 1. Summary

`refreshenv` remove environment variables [**configured in the `environment` section**](https://github.com/appveyor/ci/issues/1333#issuecomment-281462356) of the `appveyor.yml`.

@sschuberth, do you have any better ideas?

### 2. MCVE

Part of the `appveyor.yml`:

```yaml
environment:
  PATH: "%PYTHON%;%PYTHON%\\Scripts;$(PATH)"
  PYTHON: C:\Python312-x64
  ```
  
1. [**`echo %PATH%` before `refreshenv`**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49063493#L21)
1. [**`echo %PATH%` after `refreshenv`**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49063493#L25)

After `refreshenv` no `C:\Python312-x64;C:\Python312-x64\Scripts;` in `PATH`.

### 3. Why refreshenv matters

Because AppVeyor users can install programs that add new directories to `PATH`. Without tools like refreshenv, AppVeyor users cannot use CLI commands from new directories added to `PATH`. AppVeyor doesn’t automatically update the values of the `PATH` environment variable for the next CLI commands.

For example, I want to install [**gnuplot**](http://www.gnuplot.info/):

```text
choco install --yes gnuplot
```

[**Without refreshenv**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49064085#L46):

```text
where gnuplot
INFO: Could not find files for the given pattern(s).
Command exited with code 
```

[**After refreshenv**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49064119#L48):

```text
where gnuplot
C:\Program Files\gnuplot\bin\gnuplot.exe

gnuplot --version
gnuplot 5.4 patchlevel 8
```

### 4. Solutions

For my MCVE.

#### 4.1. Third-party tools

I use [**pathed**](http://www.p-nand-q.com/download/gtools/pathed.html):

```sh
# https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49064979
choco install --yes gtools
refreshenv
pathed /ADD %PYTHON% /MACHINE
pathed /ADD %PYTHON%\Scripts /MACHINE
choco install --yes gnuplot
refreshenv
```

It works, but it would be nice to have a better solution. Before executing all commands, the user must install `pathed` and run the `refreshenv` command after `pathed` installation.

#### 4.2. Manually setting all environment variables

To avoid using refreshenv:

```yaml
# https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/49064460
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  PATH: "%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\gnuplot\\bin;$(PATH)"
  PYTHON: C:\Python312-x64
```
  
The problem with this approach is that in real large projects the user might be required to manually add many directories to the `environment:PATH` section of the `appveyor.yml` instead of using a single `refreshenv` command.

Thanks.
