### ISSUE TITLE
Strangely uppercased environment variable

### ISSUE THREAD

**Issue by srazi** [appveyor/ci#1349]
My project appveyor.yml contains:
```yml
environment:
  global:
    MAKETOOL: jom
    TOOLSDIR: C:\Qt\Tools\QtCreator
    PLATFORM: x86

  matrix:
    - QTVER: 5.7
      QTDIR: C:\Qt\5.7\msvc2015
      QMAKESPEC: win32-msvc2015
      VSVER: 14
    - PLATFORM: x64
      QTVER: 5.7
      QTDIR: C:\Qt\5.7\msvc2015_64
      QMAKESPEC: win32-msvc2015
      VSVER: 14
```

It correctly will be set to `x86` but in second job strangely it will be set to `X64` (uppercase X)
