### ISSUE TITLE
Evaluate variables value in matrix/env vars

### ISSUE THREAD

**Issue by am11** [appveyor/ci#1378]
In appveyor.yml:

```yml
environment:
  global:
    MYDIR: $env:APPVEYOR_BUILD_FOLDER/TEST/SPECS
    OR: $APPVEYOR_BUILD_FOLDER/TEST/SPECS
```

does not evaluate the variable `$env:APPVEYOR_BUILD_FOLDER` or `$APPVEYOR_BUILD_FOLDER`. Instead, we need to update it manually:

```yml
environment:
  global:
    MYDIR: TEST/SPECS

build_script:
  - ps: |
      $env:MYDIR = "$env:APPVEYOR_BUILD_FOLDER/$env:MYDIR"
```

In contrast, `.travis.yml` allows this:

```yml
env:
  global:
    - MYDIR=$TRAVIS_BUILD_DIR/TEST/SPECS
```

Would be nice to have this ability.
