### ISSUE TITLE
Visual Studio 2017 update 15.0.26228.9

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1411]

**Comment by onovotny** [comment]
Possibly related to this, but it seems like some of the android API's are missing from the image? In the Android SDK manager, have all of the API's been enabled?

API 24, at the very least, seems missing, others may be too:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/243#issuecomment-287574076

**Comment by FeodorFitsner** [comment]
Is it installed with VS 2017 installer?

**Comment by onovotny** [comment]
The VS 2017 installer does not install all android SDK's :(. From within VS, you can launch the Android SDK manager (a Google tool) and select the SDK's to install.

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
We are going to deploy both API 24 and 25 to Visual Studio 2017 image, but for now you can install API 24 during the build with the following script:

```yaml
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-android-sdk.ps1?v=2'))
- ps: $sdks = Get-AndroidSDKs |? { $_.name -like 'sdk platform*API 24*' -or $_.name -like 'Google APIs, Android API 24' } 
- ps: Install-AndroidSDK -sdks $sdks
```
