### ISSUE TITLE
Documentation on APPVEYOR_BUILD_WORKER_IMAGE

### ISSUE THREAD

**Issue by mloskot** [appveyor/ci#1469]
TL;TR: The `APPVEYOR_BUILD_WORKER_IMAGE` was introduced in #1417, but it was not fully documented.

-----

The only doc about this env var is https://www.appveyor.com/docs/environment-variables/ which, kind of, suggests it's read-only variable.

Ilya's answer in the Help thread [Question regarding Build Matrices and Visual Studio](http://help.appveyor.com/discussions/questions/2985-question-regarding-build-matrices-and-visual-studio#comment_41739008) suggests the variable is read-write and can be used to tweak (or request) actual build worker image.

Similar suggestion was posted in https://github.com/appveyor/ci/issues/1179#issuecomment-286696616  followed by docs update was 'promise' https://github.com/appveyor/ci/issues/1179#issuecomment-263431893 which seems like never made it to the docs.

-----

Given the multitude of Visual Studio's available and single `appveyor.yml` to configure all of them, importance of `APPVEYOR_BUILD_WORKER_IMAGE` variable seems to be critical, so it should rather be well documented on if/when/how to use it properly in order to support builds w/ multiple VS versions, etc.

Would it be possible to make the docs update?

**Comment by IlyaFinkelshteyn** [comment]
Sorry for confusion. This variable is not standard. It both “tweak” and “read”. 
 
“Read” part is what we want to advertise (and this is documented). It just displays current working image, so it can be used during the build to and answer “where am I” question.
 
“Tweak” part was introduced for special cases when some image is not publicly available, and specific customer need to use it. However even for that case we now have better solution still based on `image:` setting and we do not remove “tweak” functionality of `APPVEYOR_BUILD_WORKER_IMAGE` only because we do not want to break people who are currently using it.

**Comment by msink** [comment]
```
environment:
  matrix:
    - arch: x86
      compiler: msvc2010
      backend: ninja
    - arch: x86
      compiler: msvc2010
      backend: vs2010
    - arch: x86
      compiler: msvc2015
      backend: ninja
    - arch: x86
      compiler: msvc2015
      backend: vs2015
    - arch: x86
      compiler: msys2-mingw
      backend: ninja
    - arch: x64
      compiler: msvc2017
      backend: ninja
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - arch: x64
      compiler: msvc2017
      backend: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - arch: x64
      compiler: msys2-mingw
      backend: ninja
```
[meson-build](https://github.com/mesonbuild/meson/blob/master/.appveyor.yml)

Is something like this possible without that hack with `APPVEYOR_BUILD_WORKER_IMAGE`?

**Comment by IlyaFinkelshteyn** [comment]
@mloskot  @msink I tried to make something work for @msink using recently implemented [Exclude configuration from the matrix](https://www.appveyor.com/docs/build-configuration/#exclude-configuration-from-the-matrix) and managed to make it work, but this looks too complicated. I believe that hack with `APPVEYOR_BUILD_WORKER_IMAGE` is actually nicer so I will document "tweak" side of this variable. 
I will keep this issue open and assigned to myself while documenting.
Here is how complicated it would look if you do not use hack/tweak and I don't believe you like it:

```yaml
image:
- Visual Studio 2015
- Visual Studio 2017
environment:
  matrix:
    - arch: x86
      compiler: msvc2010
      backend: ninja

    - arch: x86
      compiler: msvc2010
      backend: vs2010

    - arch: x86
      compiler: msvc2015
      backend: ninja

    - arch: x86
      compiler: msvc2015
      backend: vs2015

    - arch: x86
      compiler: msys2-mingw
      backend: ninja

    - arch: x64
      compiler: msvc2017
      backend: ninja
      #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - arch: x64
      compiler: msvc2017
      backend: vs2017
      #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - arch: x64
      compiler: msys2-mingw
      backend: ninja

matrix:
  exclude:
    - image: Visual Studio 2017
      arch: x86
      
    - image: Visual Studio 2017
      compiler: msys2-mingw
      
    - image: Visual Studio 2015
      arch: x64
      compiler: msvc2010      
      
    - image: Visual Studio 2015
      arch: x64
      compiler: msvc2015
      
    - image: Visual Studio 2015
      arch: x64
      compiler: msvc2017
```
