### ISSUE TITLE
Error sending Email notification: Error sending email message

### ISSUE THREAD

**Issue by mknejp** [appveyor/ci#1568]
I have just added this to our configuration file so it is guaranteed that everyone breaking the build is notified regardless of mismatches of their AppVeyor and git email, AppVeyor settings, or not having an AppVeyor account at all.
```yaml
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
```
Now every failed build shows the error message
> Error sending Email notification: Error sending email message

As far as I can tell this follows the documentation on https://www.appveyor.com/docs/notifications/#appveyoryml-configuration (which seems to have incorrect indenting).

Adding the following to our configuration
```yaml
init:
  - echo %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
```
prints the email address, so AppVeyor has access to it.

Is this a bug on the servers or our configuration?
