### ISSUE TITLE
Track on_build_status_changed per branch

### ISSUE THREAD

**Issue by mknejp** [appveyor/ci#1578]
I don't know if this is a bug or intended behavior. We have configured notifications for our master/develop branches like this
```yaml
- branches:
    only:
      - master
  ...
  notifications:
    - provider: Email
      to:
        - '{{commitAuthorEmail}}'
      on_build_success: false
    - provider: Slack
      on_build_success: false
      incoming_webhook:
        secure: blah

- branches:
    only:
      -develop
  ...
  notifications:
    # same as above
```
It appears that the `on_build_status_changed` option (which is `true` by default) tracks the status of the entire project, not the branches selected in the section. Thus if we have a successful build on the `develop` branch following a failed build on a `feature/xxx` branch we get the notification, even if the prior build of `develop` was successful, which isn't very useful.

I would expect the `on_build_status_changed` property to be tracked per-branch if it is allowed to be configured differently per branch. If the current behavior is intended, can an option be added to change this behavior? I wouldn't mind it being a project-wide setting in the settings UI.

Due to #1568 currently in effect we get a confirmation in form of the error message that this is not a Slack-only issue but applies to both notification providers.
