### ISSUE TITLE
Support for Node v8.0.0

### ISSUE THREAD

**Issue by kunagpal** [appveyor/ci#1581]
With the following build matrix:
```yaml
   matrix:
      - node: "8"
  
   install:
      - ps: Install-Product node $env:node
```
the following error shows up:
```
node  x86 package not found
```

When will support for [Node v8.0.0](https://nodejs.org/en/blog/release/v8.0.0/) be added? 😄 

Related to #729
