### ISSUE TITLE
Installs Node 8.0.0 instead of 8.1.0

### ISSUE THREAD

**Issue by mymattcarroll** [appveyor/ci#1607]
I seem to be having issues installing Node `8.1.0`. My script is configured to install Node 6 and 8 as you can see below. It installs the latest version of 6 (`6.11.0`) but it only installs node `8.0.0` instead of the latest version of 8 (`8.1.0`).

Any suggestions?

Any one else having this issue?

### `appveyor.yml`

```yml
build: 'off'
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '8'
install:
  - ps: 'Install-Product node $env:nodejs_version x64'
  - npm install --global npm-windows-upgrade
  - npm-windows-upgrade --no-spinner --npm-version latest
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
```

### Output

```
Build started
git clone -q https://github.com/blinkmobile/server-cli.git C:\projects\server-cli
git fetch -q origin +refs/pull/240/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
Install-Product node $env:nodejs_version x64
Uninstalling node 4.8.3 (x86)...
Installing node 8.1.0 (x64)...
npm install --global npm-windows-upgrade
C:\Users\appveyor\AppData\Roaming\npm\npm-windows-upgrade -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade.js
added 82 packages in 6.527s
npm-windows-upgrade --no-spinner --npm-version latest
npm-windows-upgrade v4.0.1
Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Users\appveyor\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm...
Upgrade finished. Your new npm version is 5.0.3. Have a nice day!
npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1332 packages in 59.514s
node --version
v8.0.0
npm --version
5.0.3
npm test
```
