### ISSUE TITLE
Docker: multi-stage builds

### ISSUE THREAD

**Issue by natemcmaster** [appveyor/ci#1656]
The latest stable release of Docker Community Edition, 17.06, supports a killer new feature: multi-stage builds. (http://blog.docker.com/2017/07/multi-stage-builds/) I see AppVeyor is currently using the latest Enterprise Edition, 17.03.1-ee, which means I can't use the multi-stage build feature yet. 

Is it possible to opt-in to a newer version of Docker? I've tried installing the CE version myself from the yml file, but it fails
```yml
install:
  - ps: Invoke-WebRequest https://download.docker.com/win/stable/InstallDocker.msi -outfile docker.msi
  - start /wait msiexec /i docker.msi /qn /norestart /log install.log
os: Visual Studio 2017
```
```
This version of Docker requires Windows 10 Pro, Enterprise or Education edition with a minimum build number of 10586. Please use Docker Toolbox.
```
