### ISSUE TITLE
Visual Studio 2017 15.3.3

### ISSUE THREAD

**Issue by onovotny** [appveyor/ci#1683]
Just came out today, can the preview images please get updated?

**Comment by niemyjski** [comment]
@FeodorFitsner the final build of 15.3 is out along with dot net core 2.0!!

**Comment by FeodorFitsner** [comment]
Can you drop a link to announcement please?

**Comment by onovotny** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/

**Comment by onovotny** [comment]
also https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.1.26430.16

**Comment by FeodorFitsner** [comment]
Great news, will start working on VS 2017 image update right away!

**Comment by niemyjski** [comment]
@FeodorFitsner I was curious if you have any timeline for getting this deployed? We have a few failing builds (pull requests)

**Comment by onovotny** [comment]
@niemyjski you can install the RTW .NET Core 2 tools on the VS 2017 Preview image pretty easily: https://github.com/paulcbetts/refit/blob/master/appveyor.yml#L7-L9

**Comment by FeodorFitsner** [comment]
Sure. Tomorrow or Thursday (if anything goes wrong).

**Comment by ejsmith** [comment]
Patiently waiting... 😄

**Comment by FeodorFitsner** [comment]
An updated `Visual Studio 2017` image has been published with Visual Studio 2017 15.3.

**Comment by onovotny** [comment]
Does it have .NET Core 2 SDK on it as well? :)

**Comment by FeodorFitsner** [comment]
Absolutely!

**Comment by ejsmith** [comment]
@FeodorFitsner is there any sort of .net core detection where we don't need to override the build and test steps in our appveyor.yml files or do we still need to do that?

**Comment by FeodorFitsner** [comment]
@ejsmith could you please elaborate what you mean?

**Comment by ejsmith** [comment]
I mean right now I am doing this:

```yaml
build_script:
  - ps: dotnet build -c Release

test_script:
  - ps: dotnet test .\test\Foundatio.Parsers.LuceneQueries.Tests\Foundatio.Parsers.LuceneQueries.Tests.csproj -c Release

after_test:
  - ps: dotnet pack -c Release
```

Whereas in old style C# projects the appveyor defaults would pick up my project, build and test it the proper way.
