### ISSUE TITLE
Documentation on common configuration merging is slightly incorrect

### ISSUE THREAD

**Issue by ArseniyShestakov** [appveyor/ci#1703]
Related to new feature in recently closed #325. Project I work on is extremely heavy to build so we using just 1-2 different builds on commits. Though I wanted to have special branch that will trigger build with all possible configurations and toolchains.

I'm tried to use new feature of sharing common configuration as explained in documentation:
https://www.appveyor.com/docs/branches/#sharing-common-configuration-between-branches
So this specific line seems to be wrong or misleading:
```Build matrix defined on branch level overrides default one;```

With this configuration I expected special branch to trigger only 8 jobs:
```
# Common configuration for all branches
version: 1.0.{build}
max_jobs: 2
clone_depth: 10
clone_folder: c:\projects\vcmi\source
environment:
  matrix:
    - NAME: MSVS 2015 x86 - Release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCMI_GENERATOR: Visual Studio 14 2015
      VCMI_BUILD_PLATFORM: x86
      VCMI_BUILD_CONFIGURATION: Release
    - NAME: MSVS 2017 x64 - Release
..
install:
- bash c:\projects\vcmi\source\CI\msvc\install.sh
build_script:
- cmd: c:\projects\vcmi\source\CI\msvc\build_script.bat
artifacts:
- path: build_$(BUILD_PLATFORM)\*.exe
notifications:
  - provider: Slack
    incoming_webhook:
      secure: zxT3HTnxL744HiSv7ig7sjGL4LmJ8n3MsY8PEA/kinbVMkmcxrSgVBVkHV79RfSWSyq4oLMSRvMMpG8SuDWnf6oK/qvgaiAWfwwlCIiA7uQ=

# Branch-specific configuration
for:
# Extended configuration for toolchain_test branch
-
  branches:
    only:
      - appveyor/vcpkg
  environment:
    matrix:
      - NAME: MSVS 2015 x86 - Release
..
      - NAME: MSVS 2015 x86 - Debug
..

      - NAME: MSVS 2015 x64 - Release
..
      - NAME: MSVS 2015 x64 - Debug
..

      - NAME: MSVS 2017 x86 - Release
..
      - NAME: MSVS 2017 x86 - Debug
..

      - NAME: MSVS 2017 x64 - Release
..
      - NAME: MSVS 2017 x64 - Debug
..
```
Instead it triggered 10 different jobs (should be just 8 since base matrix supposedly should be ignored):
https://ci.appveyor.com/project/vcmi/vcmi/build/1.0.311

Am I reading this line wrong or documentation is incorrect?

**Comment by ArseniyShestakov** [comment]
I find out that if I move my default all-branches configuration into "for:" it's no longer merged with one specific for toolchain_test:
```
# Common configuration for all branches
version: 1.0.{build}
max_jobs: 2
clone_depth: 10
clone_folder: c:\projects\vcmi\source
install:
- bash c:\projects\vcmi\source\CI\msvc\install.sh
build_script:
- cmd: c:\projects\vcmi\source\CI\msvc\build_script.bat
artifacts:
- path: build_$(BUILD_PLATFORM)\*.exe
notifications:
  - provider: Slack
    incoming_webhook:
      secure: zxT3HTnxL744HiSv7ig7sjGL4LmJ8n3MsY8PEA/kinbVMkmcxrSgVBVkHV79RfSWSyq4oLMSRvMMpG8SuDWnf6oK/qvgaiAWfwwlCIiA7uQ=

# Branch-specific configuration
for:
# Extended configuration for toolchain_test branch
-
  branches:
    only:
      - appveyor/vcpkg
  environment:
    matrix:
      - NAME: MSVS 2015 x86 - Release
..
      - NAME: MSVS 2015 x86 - Debug
..

      - NAME: MSVS 2015 x64 - Release
..
      - NAME: MSVS 2015 x64 - Debug
..

      - NAME: MSVS 2017 x86 - Release
..
      - NAME: MSVS 2017 x86 - Debug
..

      - NAME: MSVS 2017 x64 - Release
..
      - NAME: MSVS 2017 x64 - Debug
..

-
  environment:
    matrix:
      - NAME: MSVS 2015 x86 - Release
..
      - NAME: MSVS 2017 x64 - Release
..
```
I suppose this could easily be intended and I just misunderstand documentation.
Probably some better example would be helpful.
