### ISSUE TITLE
.NET Core SDK 2.0.0 runtime x86 into Visual Studio 2017 image

### ISSUE THREAD

**Issue by dmitriyse** [appveyor/ci#1742]
The current workaround:
``` yaml
install:
  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x86.exe
  - cmd: dotnet-sdk-2.0.0-win-x86.exe /install /quiet /norestart /log install.log
```

**Comment by IlyaFinkelshteyn** [comment]
@dmitriyse It was just added in the end of the last week: https://www.appveyor.com/updates/2017/08/17/.  I think you can safely try without this workaround.

**Comment by dmitriyse** [comment]
Hi! Thank you for fast response.
But I tried just some minutes ago and received:

term 'c:\Program files (x86)\dotnet\dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is  correct and try again.

But it works with the workaround.

**Comment by dmitriyse** [comment]
Probably you added only x64 version.
But it's not enough for real cross platform project.

**Comment by IlyaFinkelshteyn** [comment]
You can compile for any platform with x64 version of `dotnet.exe`, isn't it? You can select any runtime from the [rid catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) with `-r|--runtime` switch. Correct me if I wrong.

**Comment by dmitriyse** [comment]
Unfortunately no.
If you have published x86 bound project in "Framework Dependent Mode" (https://docs.microsoft.com/en-us/dotnet/core/deploying/index), than you need to execute it with "dotnet myproject.dll" command.
This type of command does not supports --runtime option.
So dotnetcore-sdk x64 is capable to build and publish x86 binaries, but not execute it.
(probably dotnetcore-runtime-x86 is enough to execute x86 binaries I did not tested this yet)

**Comment by dmitriyse** [comment]
To execute dotnetcore 2.0 x86 binaries, dotnetcore-2.0 x86 runtime should be installed:
```Yaml
install:
  - cmd: curl -O https://download.microsoft.com/download/5/6/B/56BFEF92-9045-4414-970C-AB31E0FC07EC/dotnet-runtime-2.0.0-win-x86.exe
  - cmd: dotnet-runtime-2.0.0-win-x86.exe /install /quiet /norestart /log install.log
```
Please add x86 runtime right into the image.
