### ISSUE TITLE
Build fails on 64 bit with electron-rebuild

### ISSUE THREAD

**Issue by hovancik** [appveyor/ci#1743]
Here is the build: 
https://ci.appveyor.com/project/hovancik/stretchly/build/1.0.504

It works on 32 but fails after 1 hour on 64 bit. 

my yml: 

```
build: off

os: unstable

platform:
  - x86
  - x64

skip_tags: true

environment:
  nodejs_version: "7.9.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install
  - .\node_modules\.bin\electron-rebuild
  - npm install -g istanbul

test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha

after_test:
  - bash <(curl -s https://codecov.io/bash)

```

What I added is: `.\node_modules\.bin\electron-rebuild` so I can rebuild a module I am using.
