### ISSUE TITLE
[Feature request] Patching support for .props files

### ISSUE THREAD

**Issue by ig-sinicyn** [appveyor/ci#1750]
Subj:)
We have a solution with projects that use new csproj format. Some properties are extracted into .props files to share them across all projects. The one with versions looks like this:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
...
		<Version>1.4.1.0</Version>
		<PackageVersion>1.4.1-alpha</PackageVersion>
		<PackageOutputPath>..\..\_Results</PackageOutputPath>
	</PropertyGroup>
</Project>
```
I've tried to patch it with these lines in `appveyor.yml`:
```
dotnet_csproj:
  patch: true
  file: 'Build\CodeJam.Default.props'
  version: '{buildVersion}'
  package_version: '$(nugetVersion)'
```
and got a message
```
Patching .NET Core .csproj files
Presumably Build\CodeJam.Default.props is not .NET Core .csproj file, patching skipped
No .NET Core .csproj files found
```

It's not blocker, of course, I'll workaround it with powershell script. But in future it will be nice to have version patching support out of the box:)
Also, it will be fine to support all version tags including AssemblyVersion, FileVersion and InformationalVersion (used by [GenerateAssemblyInfo](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets)).
