### ISSUE TITLE
.NET Core .csproj files patching on .fsproj (F# Project)

### ISSUE THREAD

**Issue by nikolaia** [appveyor/ci#1811]
Trying to do .NET Core project file patching on a F# project (which is basically the same project format, just a different file ending), ref https://www.appveyor.com/docs/build-configuration/#net-core-csproj-files-patching:

```
dotnet_csproj:
  patch: true
  file: '**\*.fsproj'
  version: '{version}'
  package_version: '{version}'
```

But it doesn't seem to work:
```
Presumably src\SomeProject\SomeProject.fsproj is not .NET Core .csproj file, patching skipped
No .NET Core .csproj files found
```

Would it be possible to make this work with .fsproj files (Given that it doesn't already work and I'm doing something wrong)?
