### ISSUE TITLE
csproj patcher not updating files with new version number 

### ISSUE THREAD

**Issue by clmcgrath** [appveyor/ci#1907]
I have a solution that is configured the same as all of my other .net core projects but it refuses to update my csproj files with the CI build number thus producing undeployable nuget packages as nuget needs the package version to be incremented which i am generating from the patched csproj files

build log:
```
Build started
msbuild -version
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
15.4.8.50001dotnet --version
2.0.2
git clone -q --branch=master https://github.com/DigitalParadox/Logging.git C:\projects\logging
git checkout -qf 2351d37141f153c9bc24bcdd32a03e882e8c3a70
Running Install scripts
nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
Package source "nuget.org" was successfully updated.
Patching .NET Core .csproj files
dotnet build /property:IncludeSymbols=true
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  DigitalParadox.Logging -> C:\projects\logging\src\DigitalParadox.Logging\bin\Release\netstandard2.0\DigitalParadox.Logging.dll
  Successfully created package 'C:\projects\logging\src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.nupkg'.
  Successfully created package 'C:\projects\logging\src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.symbols.nupkg'.
  DigitalParadox.Logging.Serilog -> C:\projects\logging\src\DigitalParadox.Logging.Serilog\bin\Release\netstandard2.0\DigitalParadox.Logging.Serilog.dll
  Successfully created package 'C:\projects\logging\src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.nupkg'.
  Successfully created package 'C:\projects\logging\src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.symbols.nupkg'.
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:06.73
Discovering tests...OK
Collecting artifacts...
Found artifact 'src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.nupkg' matching 'src\**\*.nupkg' path
Found artifact 'src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.symbols.nupkg' matching 'src\**\*.nupkg' path
Found artifact 'src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.nupkg' matching 'src\**\*.nupkg' path
Found artifact 'src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.symbols.nupkg' matching 'src\**\*.nupkg' path
Uploading artifacts...
[1/4] src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.nupkg (3,564 bytes)...100%
[2/4] src\DigitalParadox.Logging\bin\Release\DigitalParadox.Logging.1.0.0.symbols.nupkg (3,881 bytes)...100%
[3/4] src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.nupkg (4,667 bytes)...100%
[4/4] src\DigitalParadox.Logging.Serilog\bin\Release\DigitalParadox.Logging.Serilog.1.0.0.symbols.nupkg (5,440 bytes)...100%
Build success
```

appveyor.yaml

```
dotnet_csproj:
  patch: true
  file: '*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: dotnet build /property:IncludeSymbols=true
artifacts:
- path: src//*.nupkg
  name: nupkg
```
