### ISSUE TITLE
Commands that use single quotes not recognized anymore?

### ISSUE THREAD

**Issue by krlmlr** [appveyor/ci#1929]
I have the following in `appveyor.yml`:

```yml
install:
  - ps: Bootstrap
  - cmd: R -q -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: R -q -e "getOption('repos')"
  - cmd: R -q -e "install.packages('remotes'); remotes::install_github('ropenscilabs/tic'); tic::prepare_all_stages()"
```

Now, the first `cmd` item suddenly started throwing an error on AppVeyor:

```
R -q -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
'C:\R/bin/i386/Rterm.exe" -q -e "writeLines' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

Link to build: https://ci.appveyor.com/project/r-lib/styler/build/1.0.12#L136

I'm pretty sure this used to work correctly. Is there a better way to write this command? I also tried, with same results:

```yml
install:
- ps: Bootstrap
- cmd: |
          R -q -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"

- cmd: |
          R -q -e "getOption('repos')"

- cmd: |
          R -q -e "install.packages('remotes'); remotes::install_github('ropenscilabs/tic'); tic::prepare_all_stages()"


```
