### ISSUE TITLE
Broken .NET Core AssemblyInfo patching

### ISSUE THREAD

**Issue by bkoelman** [appveyor/ci#1972]
See failing build at https://ci.appveyor.com/project/bkoelman/testablefilesystem/build/0.1.0-pre-151-master.

```
obj\Release\net45\TestableFileSystem.Interfaces.AssemblyInfo.cs(18,59): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
obj\Release\net45\TestableFileSystem.Interfaces.AssemblyInfo.cs(22,55): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
```

I've added a custom task to the project file, which dumps the contents of the generated/patched AssemblyInfo file:

```
Contents of file 'C:\projects\testablefilesystem\src\Interfaces\obj\Release\netstandard1.3\TestableFileSystem.Interfaces.AssemblyInfo.cs':
  //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
[assembly: System.Reflection.AssemblyCompanyAttribute("Bart Koelman")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Apache License, Version 2.0")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Abstractions for System.IO.*, intended for unit-testing.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0-pre-151-master")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0-pre-151-master")]
[assembly: System.Reflection.AssemblyProductAttribute("TestableFileSystem.Interfaces")]
[assembly: System.Reflection.AssemblyTitleAttribute("TestableFileSystem.Interfaces")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0-pre-151-master")]
// Generated by the MSBuild WriteCodeFragment class.
```

Note the incorrect values for AssemblyVersionAttribute and AssemblyProductAttribute, which must be numeric only. This used to compile without errrors on previous VS2017 images.

Build succeeds when turning off .NET Core AssemblyInfo patching. 

AppVeyor configuration:
```yaml
version: 0.1.0-pre-{build}-{branch}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: msbuild /t:restore src\TestableFileSystem.sln
build:
  project: src\TestableFileSystem.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - TestableFileSystem.Fakes.Tests.dll
after_test:
- cmd: >-
    set configuration=Release

    set opencover="%USERPROFILE%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"

    set testrunner="%xunit20%\xunit.console.x86.exe"

    set targets=".\src\Fakes.Tests\bin\%configuration%\net452\TestableFileSystem.Fakes.Tests.dll .\src\Analyzer.Tests\bin\%configuration%\net452\TestableFileSystem.Analyzer.Tests.dll -noshadow -appveyor"

    set filter="+[TestableFileSystem*]*  -[TestableFileSystem.*.Tests*]*  -[TestableFileSystem.Wrappers*]*"

    set coveragefile=".\CodeCoverage.xml"


    %opencover% -returntargetcode -register:user -target:%testrunner% -targetargs:%targets% -filter:%filter% -hideskipped:All -output:%coveragefile%

    SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%

    pip install codecov

    codecov -f %coveragefile%
artifacts:
- path: '**\TestableFileSystem*.nupkg'
```
