### ISSUE TITLE
[bug] Branch-specific commands are executed on wrong branches

### ISSUE THREAD

**Issue by Korijn** [appveyor/ci#1986]
With the following configuration:

```
for:
  - branches:
      only:
        - default
    after_test:
      - some_command
```

some_command is still executed on a non-default branch. see e.g. this build: https://ci.appveyor.com/project/clinicalgraphics/dhf/build/0.1.0.dev0+113
