### ISSUE TITLE
node x86/x64 package not found

### ISSUE THREAD

**Issue by mvrahden** [appveyor/ci#2036]
Hi everybody,

I configured a matrix-job on several nodejs-versions, but two versions of them (8.9.4, 6.12.3) are constantly running into "package not found"-errors. All the other nodejs-versions are resulting green.

This is my config-fille:
```
platform:
  - x86
  - x64
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
    # Output useful info for debugging.
  - node --version
  - npm --version
  # Typical npm stuff.
  - npm install
  - npm test
build: off
cache: node_modules
environment:
  matrix:
    - nodejs_version: "9.3.0"   # same results as 9.0.x, 9.1.x, 9.2.x
    - nodejs_version: "8.9.4"   # same results as 8.7.x, 8.8.x, 8.9.x
    - nodejs_version: "8.6.0"   # same results as 8.3.x, 8.4.x, 8.5.x
    - nodejs_version: "8.2.1"   # same results as 8.0.x, 8.1.x, 8.2.x
    - nodejs_version: "7.10.1"  # same results as 7.6.x, 7.7.x, 7.8.x, 7.9.x, 7.10.x
    - nodejs_version: "7.5.0"   # same results as 7.1.x, 7.2.x, 7.3.x, 7.4.x
    - nodejs_version: "6.12.3"  # same results as 6.5.x, 6.6.x, 6.7.x, 6.8.x, 6.9.x, 6.10.x, 6.11.x, 6.12.x
    - nodejs_version: "6.4.0"   # same results as 6.0.x, 6.1.x, 6.2.x, 6.3.x
```
I checked this [node website](https://nodejs.org/en/download/releases/) for compatibility. But it seems that there are Windows-packages available.

What might be the issue here and how can I resolve it?

Cheers!

PS: Is there a convenient way to trigger single test-jobs without triggering the whole cascade of them?
