### ISSUE TITLE
Build worker reboot

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#204]

**Comment by vors** [comment]
I cannot make it work.
Here is the sample:
https://ci.appveyor.com/project/vors/psscriptanalyzer/build/1.0.11


```yml
install:
    - set TEST_VAR=Hello, world!
    - echo before reboot
    - ps: Restart-Computer -Force            # here the server goes restarting
    - echo Before sleep
    - ps: |
        Write-Host $env:TEST_VAR
        Write-Host ([datetime]::Now)
        Start-Sleep -s 10
        Write-Host "After sleep"
        Write-Host ([datetime]::Now)

build_script:
    - echo Build
    - ps: |
        Write-Host ([datetime]::Now)
        Write-Host after reboot
        Write-Host $env:TEST_VAR

test: off
deploy: off
```

According to log reboot happens in just 1 second.
