### ISSUE TITLE
Deploy script + provider?

### ISSUE THREAD

**Issue by fniephaus** [appveyor/ci#2042]
Hi, 

it looks like there can either be a `deploy_script` *or* `deploy` providers. Is there any way to combine both? Travis has a `script` provider instead of `deploy_script`.

Best,
Fabio

**Comment by IlyaFinkelshteyn** [comment]
In case you select deploy provider, `before_deploy` and `after_deploy` scripts also become available. If this does not fit into your scenario, can you describe it more, so we could propose a solution/workaround?

**Comment by fniephaus** [comment]
I think this should do the trick. Unfortunately, `before_deploy` does not support `on:` conditions in the same way a deploy provider does. If there was a script provider, I could do something like:

```yml
deploy:
  provider: Script
  path: my-script.sh
  on:
    branch: my-branch
    appveyor_repo_tag: true
```

Maybe something AppVeyor wants to support at some point.
