### ISSUE TITLE
Boost.Python linkage problem

### ISSUE THREAD

**Issue by roigcarlo** [appveyor/ci#2043]
Hi, 

I am trying to build out code using appveyor and we need boost. Specifically we need the boost.python module.
I am using the latest v1.65 you privide along with VS 2017 env and I saw that `boost_python3-vc141-mt-1_65_1.dll` is there.

For our code to link correctly we need to use the same version of python used while building the boost.python module. But after trying all python3 versions you provide none of them linked correctly.

I made a dumpbin of the boost.python lib and I obtained:
```
Dump of file C:\Libraries\boost_1_65_1\lib64-msvc-14.1\boost_python3-vc141-mt-1_65_1.dll
File Type: DLL
  Image has the following dependencies:
    python27.dll <--
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
```

Is this intended? I can move to python27 if necessary but its quite misleading that boost_python3 links against version python27.

Br.

**Comment by IlyaFinkelshteyn** [comment]
I am not familiar with boost, but I tried all Python versions on `Visual Studio 2017` with simple script in matrix [here](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/33.464.1069). Python version appears to be as expected. Or I am testing something completely unrelated?

**Comment by roigcarlo** [comment]
Python version by itself its fine, the issue is with the python version used in the boost.python lib.
While compiling boost.python 1.66 it should generate at least 2 versions of the lib (+gd variants etc...):

* boost_python-vc141-mt-1_65_1.dll
* boost_python3-vc141-mt-1_65_1.dll

Which are indeed there. The problem is that both versions of the lib seems to be linked to the same version of python 2.7 and I would have expected the python3 variant using a python3 backend

So when we link our lib which uses python 3.X against boost_python3-vc141-mt-1_65_1 which uses python 2.7 it generates a linkage problem. Specifically in this function (from [this](https://ci.appveyor.com/project/roigcarlo/kratos/build/23) build):

```
error LNK2019: unresolved external symbol "__declspec(dllimport) struct _object * __cdecl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))" (__imp_?init_module@detail@python@boost@@YAPEAU_object@@AEAUPyModuleDef@@P6AXXZ@Z)
```

If you want you should be able to reproduce it like this (Based in your build matrix):
```yml
image: Visual Studio 2017

clone_script:
- cmd: |
    SET PATH=%PYTHON_DIR%;%PATH%
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
    python -V
    dumpbin.exe /dependents C:\Libraries\boost_1_65_1\lib64-msvc-14.1\boost_python3-vc141-mt-1_65_1.dll
    
environment:
  matrix:
  - PYTHON_DIR: C:\Python26
  - PYTHON_DIR: C:\Python26-x64   
  - PYTHON_DIR: C:\Python27
  - PYTHON_DIR: C:\Python27-x64
  - PYTHON_DIR: C:\Python33
  - PYTHON_DIR: C:\Python33-x64
  - PYTHON_DIR: C:\Python34
  - PYTHON_DIR: C:\Python34-x64
  - PYTHON_DIR: C:\Python35
  - PYTHON_DIR: C:\Python35-x64
  - PYTHON_DIR: C:\Python36
  - PYTHON_DIR: C:\Python36-x64

build: off
test: off
```

This should report 2 different versions of python except in Python27 and Python27-x64

That said I understand that probably is unrealistic to provide all permutations so if this cannot be changed I will try to build our code against python 2
