### ISSUE TITLE
[Feature request][Python] Automatically set last stable version

### ISSUE THREAD

**Issue by Kristinita** [appveyor/ci#2064]
### 1. Summary

It would be nice, if would be possible, that AppVeyor can automatically set the latest Python stable version, that developers doesn't need to set specific version.

### 2. Argumentation

I develop Python packages. I want, that my packages works on latest stable Python version. Part of my example `appveyor.yml` file:

```yaml
environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64
```

When new Python version release, I need to change `3.6.4` to `3.6.5` in each my project, then I should change value to `3.6.6`, `3.7.0` and so on. It may take a lot of time.

### 3. Expected behavior

Example part of `.travis.yml`:

```yaml
environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "stable"
      PYTHON_ARCH: "64"

platform: x64
```

AppVeyor will automatically use the latest stable Python version, what is available on AppVeyor.

### 4. Examples in another apps

In Travis CI [**possible set latest nightly**](https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions) (but not stable) Python version.

Thanks.
