### ISSUE TITLE
Not trigger build on a repository with access from other user

### ISSUE THREAD

**Issue by jrgcubano** [appveyor/ci#2065]
I have access to the repository https://github.com/jagregory/fluent-nhibernate. I add it as a project on appveyor and configure everything necessary (enviroments, etc) as always, but does not launch builds after push commits, PR or tag... Is this possible or do I need another type of configuration? Or the only solution is that the owner "jagregory" configure appveyor himself?

I tried to unlink my github account, etc... but it does not work

The appveyor.yml:

```
version: '{build}'
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true
  
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

branches:
  only:
    - refs/heads/master
    - refs/tags/*
    - /r/.*/
    - master
    - develop
    - /feat/.*/
    - /fix/.*/

# clone_depth: 1
build_script:
  - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic

test: off

cache:
- tools -> build.cake
- packages -> build.cake
```
