### ISSUE TITLE
Deployment to Github releases for Organisation seems broken

### ISSUE THREAD

**Issue by juliaogris** [appveyor/ci#2068]
Hi,

I've got a broken [Appveyor build deployment](https://ci.appveyor.com/project/anz-bank/sysl/build/1.0.101) to a Github organisation repository of which I am a maintainer. The error message is
```
Deploying using GitHub provider
Creating "Sysl v0.1.2" release for repository "anz-bank/sysl" tag "v0.1.2" commit "ccd6748a759fa292745553e1c1c03d75278682cd"...
Error creating GitHub release: Error reading repository 'anz-bank/sysl' releases: 
401 - Unauthorized
```
However if I try to create the release through the Github API I do not have such an issue:

```
curl -H "Authorization: token <REDACTED>" -H "Content-Type: application/json" \
  -d '{"tag_name": "v0.1.2", "target_commitish": "master", "name": "Sysl v0.1.2", "body": "Description of the release", "draft": true, "prerelease": true}' \
  https://api.github.com/repos/anz-bank/sysl/releases
```

The relevant section of the appveyor.yml is
```
deploy:
    provider: GitHub
    release: Sysl $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    artifact: dist\sysl.exe
    draft: true
    prerelease: true
    repository: anz-bank/sysl
    auth_token:
      secure: VYvPZaOdYzBG/RS83uX0pS2uldZPq6xA59c2lllyrr5Vnm/V3aE451es8OKGUkLh
    on:
      appveyor_repo_tag: true
```

I have definitely created `VYvPZaOdYzBG/RS83uX0pS2uldZPq6xA59c2lllyrr5Vnm/V3aE451es8OKGUkLh` with `<REDACTED>` on https://ci.appveyor.com/tools/encrypt (I've repeated the step twice to be certain).

Any help much appreciated!
