### ISSUE TITLE
Skip commit except push tag

### ISSUE THREAD

**Issue by DrSensor** [appveyor/ci#2091]
Please support this config to avoid duplicate build when doing push tag.

```yml
skip_commits:
  message: /\[release\]/
  except:
    appveyor_repo_tag: true
```
