### ISSUE TITLE
for.matrix.only/.except construction in appveyor.yml

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2125]
Customers who test Linux builds asked if it is possible to use `Msbuild` mode for Windows builds and `build_script` for Linux ones. It is not possible now (current workaround is to go for `build_script` for both). With `images` in `for` construct we can achieve this.

Here are sample YAMLs:

```
image:
- Visual Studio 2017
- Ubuntu

build:
  publish_wap: true
  verbosity: minimal

for:

-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - Ubuntu build script
```
