### ISSUE TITLE
Repo Rename & Case Sensitivity w/ Ubuntu

### ISSUE THREAD

**Issue by Dargmuesli** [appveyor/ci#2126]
I needed to rename my repository [Dargmuesli/PowerShell-Lib](https://github.com/Dargmuesli/PowerShell-Lib) from `powershell-lib` to `PowerShell-Lib`. I've changed the name in AppVeyor accordingly, but AppVeyor keeps cloning the project like this:

`git clone -q --branch=master https://github.com/Dargmuesli/PowerShell-Lib.git /home/appveyor/projects/powershell-lib`

The folder to which the repository is cloned to is still in lower-case. Did I forget to change something or is that out of my control?

**Comment by IlyaFinkelshteyn** [comment]
@Dargmuesli you can use custom clone folder. However if you run Windows and Linux builds side-by-side, you (at least now) should unify clone folder with the following trick:

```
clone_folder: $(clone_folder)
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    clone_folder: /home/appveyor/projects/PowerShell-Lib
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    clone_folder: c:\projects\PowerShell-Lib
``` 
Background: It is because clone folder should be absolute path. Alternative way to select image is described [here](https://www.appveyor.com/docs/build-environment/#choosing-image-for-your-builds)
