### ISSUE TITLE
Clone folder cannot be created outside of $HOME directory

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2142]
The following will fail to create a custom clone folder:

```
clone_folder: /my_clone_folder
```

Correct script:

```bash
sudo mkdir $clone_folder
sudo chown -R $(id -u):$(id -g) $clone_folder
```

Correct cleanup code:

```bash
sudo rm -rf $clone_folder
```

**Comment by SergeGautherie** [comment]
`/my_clone_folder` is fixed.

But `/my_first_folder/my_clone_folder` still has #2305

**Comment by Wasapl** [comment]
Our tests can't reproduce same issue.
Can you please share your appveyor.yml with us? You may send it via email team@appveyor.com in case you you dont want public it worldwide.

**Comment by SergeGautherie** [comment]
Result: [Test build 408](https://ci.appveyor.com/project/SergeGautherie/reactos/build/reactos.appveyor.408)
NB: Ignore `git checkout` unrelated issue.

--

Test `appveyor.yml`:
```yaml
image: Ubuntu

version: reactos.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 5
clone_folder: /my_first_folder/my_clone_folder

init:
  - sh: uname -a
  - sh: pwd
  - sh: cd /my_first_folder
  - sh: ls -la

test: off
deploy: off
```
