### ISSUE TITLE
Qt 5.10.0 msvc2015 and msvc2017 installations look broken

### ISSUE THREAD

**Issue by d1vanov** [appveyor/ci#2149]
Today my CI builds using Qt 5.10.0 msvc2015 32 bit and msvc2017 64 bits [suddenly failed](https://ci.appveyor.com/project/d1vanov/quentier/build/0.4.0-178/job/vyc7gy8m8bh7h7e4): CMake has become unable to find the installation of Qt5:
```
CMake Error at cmake/modules/QuentierSetupQt.cmake:12 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)
-- Configuring incomplete, errors occurred!
```
It's strange since I changed nothing in my cmake files and before that it used to work like a charm. I used `PATH` environment variable to specify the path to Qt installation:
```
environment:
   matrix:
       - platform: amd64_x86
         qt: msvc2015
       - platform: amd64
         qt: msvc2017_64
         APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       - platform: mingw
         qt: mingw492_32

init:
   - if not %platform%==mingw set PATH=C:\Qt\5.10.0\%qt%\bin;%PATH%
```
It used to work fine but today it did not. I tried to investigate: added the following commands to my `appveyor.yml` before the actual build to see where the cmake files from Qt installation actually reside (maybe they were relocated and CMake can't fine them?):
```
if not %platform%==mingw cd C:\Qt\5.10.0\%qt%
if not %platform%==mingw dir /s
```
The result was [as follows](https://ci.appveyor.com/api/buildjobs/ssuq4sgcehp5p4pi/log):
```
[00:01:08] if not %platform%==mingw cd C:\Qt\5.10.0\%qt%                                                                
[00:01:08] The system cannot find the path specified.
```
So it seems Qt 5.10.0 installation directory doesn't even exist to begin with.
