### ISSUE TITLE
CI_WINDOWS variable does not work in deploy phase

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#2187]
If one use `%CI_WINDOWS%` variable in deploy phase:
```yaml
deploy:
    - provider: NuGet
      api_key:
        secure: <SOME_SECRET>
      on:
        branch: 
            - master
            - /release*/
        CI_WINDOWS: true
```
then deployment tool do not see CI_WINDOWS variable defined:
```
"NuGet" deployment has been skipped as environment variable has not matched ("CI_WINDOWS" is "", should be "true")
```
