### ISSUE TITLE
Meteor support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#220]
Discussion: http://help.appveyor.com/discussions/suggestions/634-consider-adding-meteor-to-build-worker-installed-software

**Comment by bompi88** [comment]
What is the status on this?

**Comment by bompi88** [comment]
I ended up with doing something like this:

```yml
  # Download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\installMeteor.exe /passive
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force
  # Build app
  - meteor.bat build
```
