### ISSUE TITLE
Substitute environment variable in 'service' name

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2207]

**Comment by IlyaFinkelshteyn** [comment]
This will enable scenario like this:

```
environment:
 matrix:
   - sqlver: mssql2014
   - sqlver: mssql2016

services:
  - $(sqlver)
```

**Comment by photodude** [comment]
This for would also be nice
```yml
environment:
  matrix:
  - db: mssql
    driver: sqlsrv
    db_version: sql2008r2sp2
    php: 7.2
    services: mssql2008r2sp2
  - db: mssql
    driver: sqlsrv
    db_version: sql2012sp1
    php: 7.2
    services: mssql2012sp1
```
