### ISSUE TITLE
Missing colors in console

### ISSUE THREAD

**Issue by lipkau** [appveyor/ci#2208]
## Description
The console does not print the powershell `Write-Host` colors correctly on image `Visual Studio 2017` running powershell core (`pwsh`)

## Environment
[source](https://github.com/AtlassianPS/ConfluencePS/blob/a0b2a4df2115ca71394c74690a327c5deec9edd3/appveyor.yml)
```yaml
environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu
          PowershellVersion: "6.0.0"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PowershellVersion: "6.0.0"
init:
    - ps: if (-not ($env:PowershellVersion)) {$env:PowershellVersion = "5.1"}
    - ps: if (([version]$env:PowershellVersion).Major -ge 6) {$env:posh = "pwsh"} else {$env:posh = "powershell"}
build_script:
    - ps: '& $env:posh -Command "Invoke-Build"'
```

[Visual Studio 2017](https://ci.appveyor.com/project/AtlassianPS/confluenceps/build/job/wgpstmv6dkp9k3wx)
[Ubuntu - PowershellVersion: "6.0.0"](https://ci.appveyor.com/project/AtlassianPS/confluenceps/build/job/q9qyucd4r23p95tu)
[Visual Studio 2017 - PowershellVersion: "6.0.0"](https://ci.appveyor.com/project/AtlassianPS/confluenceps/build/job/emylh2xteo77o4p5)
