### ISSUE TITLE
Using "dotnet_csproj" section to patch version in non-Core .NET projects (for ClickOnce)

### ISSUE THREAD

**Issue by DarkWanderer** [appveyor/ci#2254]
Hi,

I am using AppVeyor to build and publish an open-source ClickOnce .NET application. To correctly version a ClickOnce app, I need to patch AssemblyVersion and AssemblyInformationalVersion attributes of a project.

I have tried to use following piece:
```
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
```
But the patching just skips the projects with following message:
```
Patching .NET Core .csproj files
Patching skipped for the following files: Controller\Controller.csproj, <other projects>. Reason is that presumably they are not .NET Core .csproj files.
No .NET Core .csproj files found
nuget restore
MSBuild auto-detection: using msbuild
```
I have worked around this problem by doing actual build in after_build target and passing version explicitly:
```
after_build:
- cmd: msbuild Elite-Log-Agent.sln /verbosity:minimal /m /target:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishProfile=Release /property:ApplicationVersion=%APPVEYOR_BUILD_VERSION%
```
However, I understand it as suboptimal and I think native support for regular .csproj files may be beneficial - especially since it is (at least as I see it) not too complex of a feature

Thanks!
