### ISSUE TITLE
Use multiple 'for:' to run different script depending on configuration

### ISSUE THREAD

**Issue by johlju** [appveyor/ci#2262]
I'm trying to run the same script for two different configurations where on the first configuration the script is started using Windows PowerShell, and in the second configuration the script is started using PowerShell Core. I thought that adding two 'for:' would solve this. I'm I doing it wrong, or isn't it possible? Is there another solution to this?

```yml
configuration:
    - Config1
    - Config2

for:
-
  matrix:
    only:
      - configuration: Config1

  test_script:
    - ps: Invoke-Script

for:
-
  matrix:
    only:
      - configuration: Config2

  test_script:
    - pwsh: Invoke-Script
```

**Comment by IlyaFinkelshteyn** [comment]
You do not need second `for` key. Try this:

```
configuration:
    - Config1
    - Config2

for:
-
  matrix:
    only:
      - configuration: Config1

  test_script:
    - ps: Invoke-Script

-
  matrix:
    only:
      - configuration: Config2

  test_script:
    - pwsh: Invoke-Script
```

We should have better examples in our docs.

**Comment by IlyaFinkelshteyn** [comment]
But, actually when you have only two configurations, one of them can go as default:

```
configuration:
    - Config1
    - Config2

test_script:
  - pwsh: Invoke-Script

for:
-
  matrix:
    only:
      - configuration: Config1

  test_script:
    - ps: Invoke-Script
```
