### ISSUE TITLE
Add-AppveyorTest does not work in PowerShell Core

### ISSUE THREAD

**Issue by johlju** [appveyor/ci#2263]
I'm trying to use `Add-AppveyorTest` to add a test to the Tests pane. It works for Windows PowerShell but fails for PowerShell Core. Do I need to load the module from somewhere?

```yml
test_script:
- ps: Add-AppveyorTest -Name "Windows PowerShell" -Framework NUnit -Filename pwsh.exe -Outcome Passed -Duration 1000
- pwsh: Add-AppveyorTest -Name "PowerShell Core" -Framework NUnit -Filename pwsh.exe -Outcome Passed -Duration 1000
```

PowerShell Core fails with.

```plaintext
Add-AppveyorTest : The term 'Add-AppveyorTest' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
