### ISSUE TITLE
slack webhook isn't working with the yaml config

### ISSUE THREAD

**Issue by luisrudge** [appveyor/ci#228]
![image](https://cloud.githubusercontent.com/assets/941075/7099795/2faa2a1a-dfd5-11e4-8209-9d3eb47400d6.png)

```yaml
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/{my-awesome-guid}
  channel: tech
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
```
