### ISSUE TITLE
Pusing .net  core project to Octopus

### ISSUE THREAD

**Issue by siberianguy** [appveyor/ci#2286]
I'm trying to push a .net core console app to Octopus and I can't figure out a couple of things. As I understand I need to call "dotnet publish" then pack it using octo.exe and then call PushArtifact. But the documentation is not very detailed in this specific part, so I got lost. I hope may be there's a working sample of publishing a .net core app (but not a web app as things are much easier there)

**Comment by IlyaFinkelshteyn** [comment]
Here is YAML config which works for me:

```yaml
version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: dotnet publish coreconsoleapp2 --output %appveyor_build_folder%\dist.%appveyor_build_version%
artifacts:
- path: dist.$(appveyor_build_version)
  type: OctopusPackage
deploy:
- provider: Octopus
  push_packages: true
  server: http://<reducted_url>
  api_key:
    secure: DprCBgYjrOddUOZoaHugfldKrgWUS7tC+CYK6ET4MIk=
```

Please let us know if this helps. This is sure not the only way of doing this. You can also use `7z` or `octo.exe` for packaging and publish artifacts with [command line](https://www.appveyor.com/docs/packaging-artifacts/#pushing-artifacts-from-scripts).
