### ISSUE TITLE
Enable commit filtering in specialized matrix job configuration

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2299]
Example matrix settings:

```yaml
environment:
  matrix:
  - MyVar: val1
    SkipSomeStep: false
  - MyVar: val2
    SkipSomeStep: false  
  - MyVar: val3
    SkipSomeStep: true
```

If customer provide the following:

```
MyVar: val3
SkipSomeStep: true
```

in the commit **description** (not in commit message), we will parse it, map to existing build matrix jobs, and run only 3rd matrix job.

This also will apply to other matrix dimensions, like `configuration` or `image`

**Comment by IlyaFinkelshteyn** [comment]
More straightforward YAML notation. Also introduces short `job_name` which we need anyway


Using build numbers:

```
environment:
  matrix:
    - var1: val1-1
      var2: val2-1
    - var1: val1-2
      var2: val2-2
    - var1: val1-3
      var2: val2-3
```

Commit description to run first two: `[run_only: 1, 2]`


Using `job_name`:

```
environment:
  matrix:
    - var1: val1-1
      var2: val2-1
      job_name: abc
    - var1: val1-2
      var2: val2-2
      job_name: cde
    - var1: val1-3
      var2: val2-3
      job_name: xyz
```

Commit description to run only `abc` and `cde`: `[run_only: abc, cde]`


For those who need easier notation we can enable environment variable substitution, e.g.

```
environment:
  quick_build: abc, cde
  matrix:
    - var1: val1-1
      var2: val2-1
      job_name: abc
    - var1: val1-2
      var2: val2-2
      job_name: cde
    - var1: val1-3
      var2: val2-3
      job_name: xyz
```

Commit description to run only `abc` and `cde`: `[run_only: $(quick_build)]


Also we can do black- instead of white-listing:

Commit description to run only `xyz`: `[skip_jobs: $(quick_build)]

**Comment by TravisEz13** [comment]
@IlyaFinkelshteyn The main goal would be, for example, to only run packaging related tests for Pull requests that have a packaging related change.  This can be expressed in file filters with only a bit of over application.  If we had this, we would split these tests out into a separate job we would not want to run unless the filters are met.   This approach does not make sense without the filters as the overhead of splitting it out and running it with every PR would be too expensive.

**Comment by IlyaFinkelshteyn** [comment]
@TravisEz13 thank you so much for this suggestion! This fits nicely into [specializing matrix job configuration](https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration) we implemented recently. Right now commit filtering statements inside `for.matrix.only` and `for.matrix.except` construct are ignored as they supposed to be build-wide. But we can enable this scenario. Check this YAML:

```yaml
image:
- Visual Studio 2017
- Ubuntu
skip_commits:
  author: Ilya Finkelshteyn
for:
-
  matrix:
    only:
      - image: Ubuntu
  skip_commits:
    files:
      - docs/*
```

So if `Ilya Finkelshteyn` is commit author **whole** build will be skipped. But if author is different and files in `docs` folder where changed, `Ubuntu` job will be skipped, while `Visual Studio 2017` will run.

Does this look better?

**Comment by TravisEz13** [comment]
@IlyaFinkelshteyn yes this looks better, but let's say I am using the ubuntu image multiple times... can I select the item in the matrix I'm filtering using a variable as well?

**Comment by IlyaFinkelshteyn** [comment]
Sure, see sample with additional environment variable dimension:

```yaml
image:
- Visual Studio 2017
- Ubuntu

environment:
  matrix:
    - MY_VAR: A
    - MY_VAR: B

skip_commits:
  author: Ilya Finkelshteyn
for:
-
  matrix:
    only:
      - image: Ubuntu
        MY_VAR: A
  skip_commits:
    files:
      - docs/*
```

We like the idea very much. It fits nicely to already implemented things and covers a lot of other scenarios.

P.S. Note that you can also use `APPVEYOR_BUILD_WORKER_IMAGE` “tweak” environment variable if you prefer explicit matrix notation as described [here](https://www.appveyor.com/docs/build-environment/#using-multiple-images-for-the-same-build). This `for.matrix` approach works with any matrix notation. But some people prefer it over implicit notation. It can look like this:

```yaml
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MY_VAR: A
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MY_VAR: B
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      MY_VAR: A
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      MY_VAR: B

skip_commits:
  author: Ilya Finkelshteyn
for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        MY_VAR: A
  skip_commits:
    files:
      - docs/*
```

**Comment by TravisEz13** [comment]
@IlyaFinkelshteyn  looks great, thanks

**Comment by Shreeshrii** [comment]
I would like to know if there is a way currently to run some of the builds conditionally as suggeseted below via filtering in .yml.

>we should disable the 2015 builds by commenting 2 lines, and enable them by uncommenting these lines once a month and before a release. We can also do the same to the VS 2017 32-bit build.

```
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      vs_ver: 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vs_ver: 15 2017

platform:
  - Win32
  - Win64
```
