### ISSUE TITLE
fast_finish with allow_failures result in canceled build when mandatory job succeeded 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2346]
[discussion](https://twitter.com/dantup/status/997194543127846913?s=21)
Simple repro YAML:

```
clone_script:
- cmd: echo "skip clone"
environment:
  matrix:
  - result: good
  - result: bad1
  - result: bad2
  - result: bad3
matrix:
  fast_finish: true
  allow_failures:
    - result: bad1
    - result: bad2
    - result: bad3

install:
- ps: if ($env:result -eq "bad1") {sleep 10; throw}
- ps: if ($env:result -eq "bad2") {sleep 20; throw}
- ps: if ($env:result -eq "bad3") {sleep 30; throw}

build: off
test: of
```

**Comment by d1vanov** [comment]
I seem to be running into this again [here](https://ci.appveyor.com/project/d1vanov/libquentier/build/job/tdryx4vqfb4wip56/events). I have a job within the matrix which actually deliberately fails every time but it is thus explicitly allowed to fail:
```
environment:
  matrix:                                                                                                               
    - prepare_mode: YES
<...>
matrix:                                                                                                                 
  allow_failures:                                                                                                       
    - prepare_mode: YES                                                                                                 
  fast_finish: true
```
But what actually happens is that other jobs get cancelled with the explanation "The build with fast finish option enabled has failed".
