### ISSUE TITLE
"for matrix" eats environment variables

### ISSUE THREAD

**Issue by skirmess** [appveyor/ci#2351]
The following `appveyor.yml` file generates a matrix with two jobs, where the first one overwrites the install phase. Unfortunately, in the first one the matrix environment variables are removed. That's annoying because I would like to use the matrix to install different versions of Perl in the custom install phase.

```
environment:
  ENV_VAR_1: hello_world_1
  ENV_VAR_2: hello_world_2

  matrix:
    - ENV_VAR_3: hello_world_3
      ENV_VAR_4: hello_world_4

    - ENV_VAR_3: hello_world_3a
      ENV_VAR_4: hello_world_4a

install:
  - 'echo install'
  - 'echo %ENV_VAR_1%'
  - 'echo %ENV_VAR_2%'
  - 'echo %ENV_VAR_3%'
  - 'echo %ENV_VAR_4%'

for:
  -
    matrix:
      only:
        - ENV_VAR_4: hello_world_4

    install:
      - 'echo "install (inside for)"'
      - 'echo %ENV_VAR_1%'
      - 'echo %ENV_VAR_2%'
      - 'echo %ENV_VAR_3%'
      - 'echo %ENV_VAR_4%'


build_script:
  - 'echo build_script'
  - 'echo %ENV_VAR_1%'
  - 'echo %ENV_VAR_2%'
  - 'echo %ENV_VAR_3%'
  - 'echo %ENV_VAR_4%'

test_script:
  - 'echo test_script'
  - 'echo %ENV_VAR_1%'
  - 'echo %ENV_VAR_2%'
  - 'echo %ENV_VAR_3%'
  - 'echo %ENV_VAR_4%'
```

Output from first job:

```
Running Install scripts
echo "install (inside for)"
"install (inside for)"
echo %ENV_VAR_1%
hello_world_1
echo %ENV_VAR_2%
hello_world_2
echo %ENV_VAR_3%
ECHO is off.
echo %ENV_VAR_4%
ECHO is off.
echo build_script
build_script
echo %ENV_VAR_1%
hello_world_1
echo %ENV_VAR_2%
hello_world_2
echo %ENV_VAR_3%
ECHO is off.
echo %ENV_VAR_4%
ECHO is off.
```

and from second job

```
Running Install scripts
echo install
install
echo %ENV_VAR_1%
hello_world_1
echo %ENV_VAR_2%
hello_world_2
echo %ENV_VAR_3%
hello_world_3a
echo %ENV_VAR_4%
hello_world_4a
echo build_script
build_script
echo %ENV_VAR_1%
hello_world_1
echo %ENV_VAR_2%
hello_world_2
echo %ENV_VAR_3%
hello_world_3a
echo %ENV_VAR_4%
hello_world_4a
```
