### ISSUE TITLE
for-matrix-only: environment breaks when I add a global variable

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2361]
Possibly related/duplicate of issues 2351 and/or 2359.

--

[Build 456](https://ci.appveyor.com/project/SergeGautherie/reactos/build/CI-I2361-good.reactos.appveyor.456) works as expected.
[Build 457](https://ci.appveyor.com/project/SergeGautherie/reactos/build/CI-I2361-broken.reactos.appveyor.457) is obviously broken.
The only difference is that I added
```yaml
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==
```

--

```yaml
environment:
  matrix:
    - BuildType: "vssolution"
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==

version: CI-I2361-broken.reactos.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 1
clone_folder: C:\reactos-cov

init:
  - echo I__BT="%BuildType%"
  - ps: >-
      If ($env:BuildType -eq "clang-cl") {
        $env:clang_configure_option="clang"
      } Elseif ($env:BuildType -eq "vssolution") {
        $env:clang_configure_option="VSSolution"
      } Else {
        $env:clang_configure_option=""
      }
  - echo I__CCO="%clang_configure_option%"

build_script:
  - echo BS__BT="%BuildType%"
  - echo BS__CCO="%clang_configure_option%"

test: off
deploy: off

for:
-
  matrix:
    only:
      - BuildType: "vssolution"

  build_script:
    - echo FOR__BS__BT="%BuildType%"
    - echo FOR__BS__CCO="%clang_configure_option%"
```
