### ISSUE TITLE
Export incoming webhook URL as a secure variable in Slack notification settings

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2362]
YAML with the following settings:

```
notifications:
- provider: Slack
  incoming_webhook:
    secure: <encrypted_value>
```

is supported. But `Export YAML` function exports `incoming_webhook` in clear text.
