### ISSUE TITLE
Notification url does not allow encrypted value and/or environment variable

### ISSUE THREAD

**Issue by cilerler** [appveyor/ci#2367]
Right now, there is no way to setup encrypted notification webhook through UI.
Even further using environment variable is not working neither.

![image](https://user-images.githubusercontent.com/385958/40423631-28bbb4cc-5e61-11e8-9f8d-8c7ed1c6298a.png)

![image](https://user-images.githubusercontent.com/385958/40423636-2d6ad3a4-5e61-11e8-8459-24974a262017.png)

```yml
environment:
  slack:
    secure: a2FnSHGlcoVzHDV2+FrGWHmvnHPoYWzN7q9Lz/YaZyQVx6Fr/zMT2sTV092CMsojR0cW2k34OKA=
notifications:
- provider: Slack
  incoming_webhook:
    secure: $(slack)
```
