### ISSUE TITLE
Improve "Specify which project or solution file to use" error message

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2383]
Suggested improvements to/after the error message:
- Add a comma after "use".
- Which folder?
- Which project and solution files?

--

```yaml
version: minimal-YML.reactos.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 1
clone_folder: C:\reactos-cov
```
result is
```
Build started
git clone -q --depth=1 --branch=SergeGautherie/SelfOnly_AppVeyor_VSSolution https://github.com/SergeGautherie/reactos.git C:\reactos-cov
git checkout -qf 8bc3e1b2b746b6ae5c15d6165787dcc2dbbd9f71
Specify which project or solution file to use because the folder contains more than one project or solution file.
```
