### ISSUE TITLE
Cache in Ubuntu must filter out windows-style paths and vice versa

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#2406]
I try to use cache both in Ubuntu and Windows images:
```
image:
  - Visual Studio 2017
  - Ubuntu

cache:
  - 'C:\tools\vcpkg\installed'
  - '/usr/lib/x86_64-linux-gnu/'
```

On Ubuntu cache says:
```
Updating build cache...
Cache entry not found: /home/appveyor/projects/openmvs/C:/tools/vcpkg/installed
Cache '/usr/lib/x86_64-linux-gnu' - Up to date
```
It interprets windows-style paths as local ones and tries to cache them.

On Windows cache says:
```
Updating build cache...
Cache 'C:\tools\vcpkg\installed' - Updated
Cache entry not found: C:\projects\openmvs\usr\lib\x86_64-linux-gnu
```
It interprets unix-style paths as local ones and tries to cache them.

**Comment by FeodorFitsner** [comment]
Specializing Matrix to configure different paths for win and linux: https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration

```yaml
image:
  - Visual Studio 2017
  - Ubuntu

for:
-
  matrix:
    only:
      - image: Ubuntu
  cache:
    - 'C:\tools\vcpkg\installed'
-
  matrix:
    only:
      - image: Visual Studio 2017
  cache:
    - '/usr/lib/x86_64-linux-gnu/'
```
