### ISSUE TITLE
Short-form build matrix configuration

### ISSUE THREAD

**Issue by jawshooah** [appveyor/ci#241]
Would it be possible to add the option for a short-form matrix configuration, wherein you specify the variable space, and the matrix is simply the cross product of all variables?

Something like the following is, to me, much more maintainable and readable than specifying all 12 combinations separately:

``` yaml
environment:
  nodejs_version:
    - "0.10"
    - "0.12"
    - "1"
  jdk_version:
    - "1.7_x86"
    - "1.7_x64"
    - "1.8_x86"
    - "1.8_x64"
```

This is similar to [Travis CI's matrix configuration](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix), which by default creates a build for each possible combination and allows you to include or exclude specific combinations by value.
