### ISSUE TITLE
Problem running xUnit tests on VS2017 image

### ISSUE THREAD

**Issue by TomPallister** [appveyor/ci#2501]
Hello, sorry if this is the wrong place to raise this type of question! Just tell me where is 😄 

I have problem getting an asp.net core 2.1.301 sdk project building in AppVeyor. The project is https://github.com/ThreeMammals/Ocelot/tree/feature/upgrade-netcoreapp2.1 and the build is https://ci.appveyor.com/project/TomPallister/ocelot-fcfpb/build/7.1.0-upgrade-netcoreapp2-1.1+38.build.1300.

It seems the unit tests (xunit) cannot run on the AppVeyor Visual Studio 2017 image. I'm sure this is something I'm doing wrong but I can't work it out. Any ideas? Any help would be appreciated!

**Comment by OwenMcDonnell** [comment]
Could you post your CI configuration by going to _**Settings -> Export YAML**_ tab in your project?

**Comment by TomPallister** [comment]
Thanks @OwenMcDonnell it is

```yaml
version: '{build}'
skip_tags: true
image: Visual Studio 2017
environment:
  nuget-apikey-unstable: redacted
  coveralls-repo-token-ocelot: redacted
build_script:
- ps: ./build-and-release-unstable.ps1
test: off
deploy: off
```
