### ISSUE TITLE
dotnet restore - Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by sirkadirov** [appveyor/ci#2520]
Hi! I have a problem with `dotnet restore`:
````bash
 Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='System.Security.Cryptography.ProtectedData'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='Google.Protobuf'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='System.Security.Permissions'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='System.Security.Cryptography.ProtectedData'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='System.Configuration.ConfigurationManager'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='System.Configuration.ConfigurationManager'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='NLog'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/sirkadirov-fs52bnok28im/FindPackagesById()?id='NLog'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
````
Time before, I used `nuget restore` without any problems and `unauthorized` messages...

Searched in documentation, nothing found. Any ideas on this topic?

P.S. I don't need AppVeyor NuGet feed, all packages are from official NuGet feed.

**Comment by FeodorFitsner** [comment]
Could you drop your `appveyor.yml` please?

**Comment by sirkadirov** [comment]
@FeodorFitsner Yes, of course! Thanks!
````yaml
version: 2.0.{build}
skip_tags: true
image:
- Ubuntu
- Visual Studio 2017
configuration: Release
platform: x64
init:
- ps: >-
    $base_version = 2
    $base_version_additional = 0

    $build_id = (NEW-TIMESPAN -Start ([datetime]"01/01/1970 00:00") -End (GET-DATE)).Days
    $revision_id = [int]([int](NEW-TIMESPAN -Start ((GET-DATE).Date)).TotalSeconds / 2)
    $software_version = "$($base_version).$($base_version_additional).$($build_id).$($revision_id)"

    Update-AppveyorBuild -Version $software_version
    Write-Output "AppVeyor version: $(appveyor version)"
    if ($isLinux){
    sudo add-apt-repository ppa:ok2cqr/lazarus
    sudo apt-get update > /dev/null
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  SPM_RELEASE_NIGHT: 0
services: mysql
install:
- ps: >-
    Write-Output "Restoring NuGet packages..."
    dotnet nuget locals --clear all
    dotnet restore
    Write-Output "Restoring NuGet packages completed!"
nuget:
  account_feed: true
  project_feed: true
build_script:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER
    Write-Output "Current directory: $($env:APPVEYOR_BUILD_FOLDER)"
    Write-Output "Writing current directory listing to the standard output..."
    ls
    Write-Output "Building solution with DotNET MSBuild..."
    dotnet msbuild SimplePM_Server.sln /p:Configuration=Release
    Write-Output "Building process finished!"
test_script:
- ps: .\mysql_setting.ps1
deploy_script:
- ps: >-
    Write-Output "Getting ready for artifacts deployment..."

    $output_path = "SimplePM_Server-build.zip"
    $input_files = "@build_files.txt"

    Write-Output "Creating files archive with 7Zip:"
    7z a -tzip -mx=9 -bd $output_path $input_files
    Write-Output "Now we need to push artifacts to AppVeyor CI. Let's do it!"
    Push-AppveyorArtifact SimplePM_Server-build.zip -Verbosity Normal
    Write-Output "Deployment process finished!"
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
````
