### ISSUE TITLE
YAML validator displays an error in popup message

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2528]
The message then disappears in a few seconds.

Sample YAML:

```yaml
# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"

platform:
  - CommandPrompt
  - PowerShell

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  # Workaround for npm/npm#10343 when dependency of linked module is moved to dependent
  # module's 'node_modules' In our case 'cordova-common' -> jshint' -> 'cli' dependency
  # is moved to 'cordova-lib' and hence 'npm run jshint' on 'cordova-common' is failing
  #- cd cordova-common
  #- npm install
  #- cd ../cordova-fetch
  #- npm install
  #- npm link ../cordova-common
  #- cd ../

build: off

test_script:
  # Workaround for https://github.com/appveyor/ci/issues/2420
  - set "PATH=%PATH%;C:\Program Files\Git\mingw64\libexec\git-core"
  - node --version
  - npm --version

for:
-
  matrix:
    only:
      - platform: CommandPrompt

  test_script:
  - cmd: "npm test"

 -
  matrix:
    only:
      - platform: PowerShell

    test_script:
    - ps: "npm test"
```
