### ISSUE TITLE
Publishing to Azure App Service with Zip Push Deploy not deploying anything

### ISSUE THREAD

**Issue by CedricAgoda** [appveyor/ci#2545]
I'm trying to use the ZipDeploy feature available in AppVeyor. Here is my yaml fragment:
```
artifacts:
- path: publish
deploy:
- provider: AzureAppServiceZipDeploy
  appservice_environment: false
  website: mywebsitename
  username: $myusername
  password:
    secure: AABBCCDDEEFF1122334455==
```

Note I tried changing the username to be `websitename\$username` (also without `$`) and password is correct encrypted one.

It always says the upload is successful:
![image](https://user-images.githubusercontent.com/25336771/43358354-7988ae72-92ba-11e8-8cdc-2afbf20f536a.png)

but I see nothing deployed in Azure.

Is there anything else needed. My build is found here
https://ci.appveyor.com/project/CedricAgoda/opensource-ci
