### ISSUE TITLE
Temporary files: Permission denied

### ISSUE THREAD

**Issue by felixdivo** [appveyor/ci#2547]
I am trying to write some temporary files using Python's `NamedTemporaryFile` and alike, and get errors:

```
IOError: [Errno 13] Permission denied: 'c:\\projects\\python-can\\test\\__tmpdir__\\tmpj6uyhy.asc'
```

This occurs in the python-can repo, for example [right here](https://ci.appveyor.com/project/hardbyte/python-can/build/1.0.708/job/7pvkn8vvvchjet27#L289). The .appveyor.yml file looks like this:

```
environment:
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

    # Python 3.3 has reached EOL

install:
  # Prepend Python installation to PATH
  - set PATH=%PYTHON_INSTALL%;%PATH%

  # Prepend Python scripts to PATH (e.g. py.test)
  - set PATH=%PYTHON_INSTALL%\\Scripts;%PATH%

  # We need to install the python-can library itself
  - "python -m pip install .[test,neovi]"

build: off

before_test:
  # see: https://help.appveyor.com/discussions/problems/938-getting-permission-denied-errors-when-trying-to-make-a-temp-directory
  # TMPDIR is used by Python to detect the temporary directory: https://docs.python.org/3/library/tempfile.html#tempfile.tempdir
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\test\__tmpdir__
  - mkdir %TMPDIR%
  - icacls %TMPDIR% /inheritance:r /grant Everyone:(OI)(CI)F

test_script:
  - "pytest"
  - "codecov"

after_test:
  - rmdir /S /Q %TMPDIR%
```

Note: The `before_test` section was added in hope to solve the problem, but didn't help.
