### ISSUE TITLE
CreateProcess Failed on Windows 2016 But Works Fine on Windows 2012

### ISSUE THREAD

**Issue by hzxie** [appveyor/ci#2593]
I want to test a Windows API named `CreateProcess`.
But I got an error message on Windows Server 2016:
```
java.lang.Error: 
API:     CreateProcess
Code:    1326
Message: The user name or password is incorrect.
```
Please see: https://ci.appveyor.com/project/hzxie/voj/build/1.0.118/job/on2m5fml5i16c716

But it works fine in Windows Server 2012.
More strangely, I connected to the server with RDP and ran the tests manually.
All tests can be passed on Windows Server 2016 (Look at the figure below).

<img width="1280" alt="screen shot 2018-08-29 at 10 40 28 am" src="https://user-images.githubusercontent.com/1730504/44762280-19f9e480-ab79-11e8-8c46-8f65b1cba911.png">

What's wrong with it?
Thank you.

**Comment by hzxie** [comment]
Here's the `appveyor.yml`:

```
# # version: "{branch} {build}"
image:
# Windows Server 2012
- Visual Studio 2015
# Windows Server 2016
- Visual Studio 2017

environment:
  appveyor_build_worker_cloud: gce
  appveyor_rdp_password: Fx8eHPNesxhpmdru
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10

services:
  - mysql

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set MINGW_HOME=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64
  - set PATH=%MINGW_HOME%\bin;C:\cygwin64\bin;C:\Program Files\MySql\MySQL Server 5.7\bin;%PATH%
# Fix bug for mkdir in AppVeyor
  - del "C:\Program Files\Git\usr\bin\mkdir.exe"
# Fix path error for make
  - copy "C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin\mingw32-make.exe" "C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin\make.exe"
# Fix path error on JNI headers
  - copy "C:\Program Files\Java\jdk1.8.0\include\win32\jni_md.h" "C:\Program Files\Java\jdk1.8.0\include\jni_md.h"
  - copy "C:\Program Files\Java\jdk1.8.0\include\win32\jawt_md.h" "C:\Program Files\Java\jdk1.8.0\include\jawt_md.h"
  - copy "C:\Program Files\Java\jdk9\include\win32\jni_md.h" "C:\Program Files\Java\jdk9\include\jni_md.h"
  - copy "C:\Program Files\Java\jdk9\include\win32\jawt_md.h" "C:\Program Files\Java\jdk9\include\jawt_md.h"
  - copy "C:\Program Files\Java\jdk10\include\win32\jni_md.h" "C:\Program Files\Java\jdk10\include\jni_md.h"
  - copy "C:\Program Files\Java\jdk10\include\win32\jawt_md.h" "C:\Program Files\Java\jdk10\include\jawt_md.h"
# Setup test environment for Windows
  - copy "judger\src\test\resources\voj-test-windows.properties" "judger\src\test\resources\voj-test.properties"

build: off

before_test:
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');" --user=root --password=Password12!
  - mysql -e "CREATE DATABASE test;" --user=root
  - mysql test < voj.sql --user=root

test_script:
  - mvn test -f web\pom.xml
  - mvn test -f judger\pom.xml

after_test:
  - mysql -e "DROP DATABASE test;" --user=root

on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

matrix:
  fast_finish: false

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
```
