### ISSUE TITLE
Qt 5.11.1 MSVC 2017 suddenly can't find QtWebEngine

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [appveyor/ci#2599]
I have suddenly started getting below error in my build:
```
Build started
if %VCARCH% == x86 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %VCARCH% ) else ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %VCARCH% )
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
git clone -q --branch=master git@github.com:xxxxxx/xxxxxx.git C:\projects\xxxxxx
git checkout -qf 27a9a6ad92d504333a46c177055fdd6ed4083532
set PATH="%QTDIR%\bin";%PATH%;"C:\Program Files (x86)\Inno Setup 5"
mkdir "%APPVEYOR_BUILD_FOLDER%-build"
qmake CONFIG+=release -o "%APPVEYOR_BUILD_FOLDER%-build" "%APPVEYOR_BUILD_FOLDER%"
Info: creating stash file C:\projects\xxxxxx-build\.qmake.stash
Project ERROR: Unknown module(s) in QT: webenginewidgets
Command exited with code 3
```

Envrionment:
```
APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2017
OPENSSL_DIR=C:\OpenSSL-Win64
QTDIR=C:\Qt\5.11.1\msvc2017_64
VCARCH=amd64
```

appveyor.yml
```
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      OPENSSL_DIR: C:\OpenSSL-Win32
      QTDIR: C:\Qt\5.10.1\msvc2015
      VCARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      OPENSSL_DIR: C:\OpenSSL-Win64
      QTDIR: C:\Qt\5.11.1\msvc2017_64
      VCARCH: amd64

branches:
  only:
    - master

init:
  - if %VCARCH% == x86 (
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %VCARCH%
    ) else (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %VCARCH%
    )

before_build:
  - set PATH="%QTDIR%\bin";%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - mkdir "%APPVEYOR_BUILD_FOLDER%-build"

build_script:
  - qmake CONFIG+=release -o "%APPVEYOR_BUILD_FOLDER%-build" "%APPVEYOR_BUILD_FOLDER%"
  - cd /d "%APPVEYOR_BUILD_FOLDER%-build"
  - nmake
  - cd /d "%APPVEYOR_BUILD_FOLDER%"

after_build:
  - call "%APPVEYOR_BUILD_FOLDER%\deploy\deploy-windows.bat"
```
