### ISSUE TITLE
Conditional build runs the wrong matrix

### ISSUE THREAD

**Issue by ofek** [appveyor/ci#2608]
Build: https://ci.appveyor.com/project/Datadog/integrations-core/build/master.7571
PR: https://github.com/DataDog/integrations-core/pull/2163

You'll notice it creates the matrix and runs the `test_script` that is supposed to only occur on master, not pull requests (default config).

cc @FeodorFitsner @IlyaFinkelshteyn Am I doing something wrong?

```yaml
version: '{branch}.{build}'
clone_depth: 3
build: off
test: off
skip_branch_with_pr: true
cache:
  - '%LOCALAPPDATA%\pip\Cache'
services:
  - iis
  # We can't start more than one MSSQL instance to avoid conflicts on TCP port 1433. The only workaround to test a check
  # against multiple versions is letting the test code to start/stop the corresponding services so that they run one at
  # a time. See https://www.appveyor.com/docs/services-databases/ for details.
  - mssql2008r2sp2

environment:
  PYTHON2: C:\Python27-x64
  PYTHON3: C:\Python36-x64

init:
  # Add Python 3 to PATH
  - set PATH=%PYTHON3%;%PYTHON3%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Add Python 2 to PATH before Python 3
  - set PATH=%PYTHON2%;%PYTHON2%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

install:
  - python -m pip install --upgrade --disable-pip-version-check pip virtualenv codecov
  - pip uninstall -y docker-py
  - pip install .\datadog_checks_dev[cli]
  - ddev config set core .

test_script:
  # Only test any of these that have changed for pull requests
  - ddev test --changed datadog_checks_base active_directory aspdotnet dotnetclr exchange_server iis pdh_check sqlserver win32_event_log windows_service wmi_check

# Uncomment the following to enable RDP connection into the builder and debug a build
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

for:
  -
    branches:
      only:
        - master

    environment:
      PYTHON2: C:\Python27-x64
      PYTHON3: C:\Python36-x64

      matrix:
        - CHECK: datadog_checks_base
        - CHECK: active_directory
        - CHECK: aspdotnet
        - CHECK: dotnetclr
        - CHECK: exchange_server
        - CHECK: iis
        - CHECK: pdh_check
        - CHECK: sqlserver
        - CHECK: win32_event_log
        - CHECK: windows_service
        - CHECK: wmi_check

    test_script:
      - ddev test %CHECK%
```

**Comment by IlyaFinkelshteyn** [comment]
Branch for Pull Request builds is **target** (or **base**) branch, e.g. `master` in most cases. So it is expected behavior.

Very simple solution to this problem is to condition this script with `APPVEYOR_PULL_REQUEST_NUMBER` [environment variable](https://www.appveyor.com/docs/environment-variables/). It is not defined in non-PR builds.

FYI: In the [recent blob post](https://www.appveyor.com/blog/2018/08/22/bitbucket-pull-requests/) related to BitBucket PRs support, we made a very simple introduction to PR builds.

Let us know if this helps.

**Comment by IlyaFinkelshteyn** [comment]
No... You can think of creating 2 AppVeyor projects connected to the same repository, each set to use custom YAML file name. For one project disable `pushes` in GitHub Webhook setting, for another disable `pull_requests`. Though this is a bit of hack...

**Comment by ofek** [comment]
@IlyaFinkelshteyn I see. Sorry to bother but one last question: here you said it is possible https://help.appveyor.com/discussions/questions/6104-how-to-use-different-build-matrix-on-different-branches

That is exactly what I need: a matrix for commits to master and no matrix for pull requests. Can this be done?

**Comment by ofek** [comment]
Ah great! So if I remove `skip_branch_with_pr: true` I can somehow disable the matrix for pull requests? Can you please show me a tiny example?

**Comment by ofek** [comment]
@IlyaFinkelshteyn Do I have that right?

**Comment by IlyaFinkelshteyn** [comment]
Not sure. If you remove `skip_branch_with_pr: true`, you will have additional builds for **feature** (other terns **head** or **source**) branches where Pull request original change created and updated. For build you mentioned in the beginning, it is branch called `appveyor`, so for example [this](https://github.com/DataDog/integrations-core/commit/b953b408a9b2b800b69baeeaf1614f89cb157f9d) will trigger separate (not PR) build for `appveyor` branch. For those you can disable the matrix based on branch name. But branch name for pull requests to `master` will be always `master`. Again pull request builds have a lot of variables (search for `pull` at https://www.appveyor.com/docs/environment-variables/ you can use to implement some conditional logic in your test script)

**Comment by ofek** [comment]
I understand now, thanks! Is there already a feature request for this? Travis supports this like:

```
stages:
  - name: test_changed
    if: type = pull_request
  - name: test
    if: (branch = master) AND (type != pull_request)
```
