### ISSUE TITLE
Conditional caching both Windows and Ubuntu

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#2646]
So, I was trying this:

```yml
cache:
  - cmd: '%APPDATA%\npm-cache\ -> appveyor.yml,package.json,package-lock.json'
  - sh: '$HOME/.npm'
```

But I couldn't make it work. Is this even implemented?
