### ISSUE TITLE
Appveyor.yml is ignored, and web settings are used instead

### ISSUE THREAD

**Issue by Stephanevg** [appveyor/ci#2689]
Hi,

I have the impression that on my repo, the appveyor.yml file isgnored. https://github.com/Stephanevg/HostsFileManagement 

I keep having the following error message:

![image](https://user-images.githubusercontent.com/6302961/46832130-8afe0000-cda5-11e8-9ce4-379dcda05d93.png)

Strangley enough, I copied the appveyor.yml and the CI script from another repository, which actually works fine.

in the file, the build is 'off':
this is the content of my [yml file](https://github.com/Stephanevg/HostsFileManagement/blob/master/Appveyor.yml)

```yml
install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force
build: off
test_script:
- ps: >- 
    .\CI\Start_CI.ps1
```

on the project settings tab, we can see that indeed, the msbuild is select.

![image](https://user-images.githubusercontent.com/6302961/46832344-11b2dd00-cda6-11e8-8bdc-fa474cc4692e.png)

I understand that it is actually using the webconfig instead of the appveyor file. Is there a way for me, to tell appveyor to ignore the webconfig?

ps: I have revoked and re added the github authorization, which didn't solved the issue.
