### ISSUE TITLE
Conditional deployment with custom script

### ISSUE THREAD

**Issue by Flamefire** [appveyor/ci#2690]
I have a custom deployment script which I added in the `deploy_script` key. How can I set conditions on it?

Background: I need to synchronize travis (Linux, OSX) and appveyor (Win32/Win64) builds. I do have a python script, which does the heavy work and works cross-platform. I still need to call it of course.

However the CI+CD does consist of tests (e.g. "Debug" configurations shall not be deployed) and actual deployment builds (some "Release" configs). Of course I want to deploy only the latter and need conditions. This can be done with `on` for all providers: https://www.appveyor.com/docs/deployment/#conditional-deployment but I'm missing something like a `Script` provider where I can add my `deploy_script` to and set the conditions.

So idea: Extend the YAML by adding a `Script` provider to `deploy`:
```
deploy:
  - provider: Script
    script: myDeploy.py somepath
    on:
      branch: master
      configuration: Release
```

Side note: I'm currently using PowerShell with an `if` at the beginning all in one entry.

- Is there a "return" command, so I can skip the rest?
- Having all in one makes failures continue instead of aborting. E.g. a `cd` fails but the following `tar` is executed although it shouldn't

Example:
```
deploy_script:
  ps:
    |
    if ($env:configuration -eq "Release" -And $env:MSVC -eq "14.0") {
      command1
      command2
    }
```

vs:
```
deploy_script:
  - ps: if ($env:configuration -eq "Release" -And $env:MSVC -eq "14.0") { return }
  - ps: command1
  - ps: command2
```
