### ISSUE TITLE
build keeps failing (ignoring the appveyor.yml file)

### ISSUE THREAD

**Issue by Stephanevg** [appveyor/ci#2699]
hi guys,

I have a weird case. I used the exact same appveyor.yml file for different repos, and one simply started to throw this message:

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

This is the yml file I am using:

```yml
image:
- Visual Studio 2015
- Ubuntu

environment:
  PSgalleryKey:
    secure: wl8DNkBd6QUSBAEWxCNTTW+cVn32ub6kWSqZxAUrpx4/QPnWYGiLWEj+ZaFp5cuA

install:
- ps: >-
    .\CI\02_Install.ps1

build: off

build_script:
    .\CI\03_Build.ps1
test_script:
- ps: >-
    .\CI\04_Tests.ps1

```

and [here](https://ci.appveyor.com/project/Stephanevg/pshtml) is the repo that uses this yml file.

It feels like it it stops reading my yml file for some reason. which is called `appveyor.yml` and located in the root of project (see on [this](https://github.com/Stephanevg/PSHTML/tree/Feature_LinuxSupport) branch)
