### ISSUE TITLE
Patching PackageReleaseNote with dotnet_csproj 

### ISSUE THREAD

**Issue by emmekappa** [appveyor/ci#2884]
It would be great to customize release note before pushing the nuget packages through something like

```
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
    package_release_note: '$(APPVEYOR_PULL_REQUEST_TITLE)' # <-- this
```
