### ISSUE TITLE
Node 12.0 support

### ISSUE THREAD

**Issue by nschonni** [appveyor/ci#2921]
Node 12.0 was released today https://nodejs.org/en/blog/release/v12.0.0/

**Comment by shiftkey** [comment]
As a workaround, there is a documented method to use whatever versions of Node you want. This helped me upgrade a couple of projects earlier in the week:

https://github.com/atom/fs-admin/blob/master/appveyor.yml

```yaml
environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "11"
  - nodejs_version: "12"

platform:
  - x86
  - x64

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install
```

**Comment by nschonni** [comment]
Thanks @shiftkey the workaround did work. I'll leave this open till the images get updated though

**Comment by IlyaFinkelshteyn** [comment]
@nschonni yes, please do not close :)

**Comment by plroebuck** [comment]
@lyaFinkelshteyn, is there a PS way to essentially do this in the `install` step?
```js
try {
  Install-Product node $env:nodejs_version $env:platform
} catch(err) {
  Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
} 
```
As Node-12 is still unavailable, `Update-NodeJsInstallation` is the only way to get it.
But since we also test against available versions, being unable to use `Install-Product` for them just adds further delay.

```yml
environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'
```
