### ISSUE TITLE
Usage environment variables in email template

### ISSUE THREAD

**Issue by TolgaKisa** [appveyor/ci#294]
Appveyor doesn't support to use environment variables in email template at now, but if it can support this it would be very nice for details notifications

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.

**Comment by ashleywb** [comment]
Is it possible to do this now?

**Comment by IlyaFinkelshteyn** [comment]
@ashleywb:
- for full implementation please watch https://github.com/appveyor/ci/issues/2079
- for workaround please follow [this](https://www.appveyor.com/docs/notifications/#adding-custom-value-to-notification). Specifically for your case it will look like this:

```yaml
build_script:
- ps: 'Add-AppveyorMessage "commit: $env:APPVEYOR_REPO_COMMIT"'
notifications:
- provider: Email
  to:
  - <your_email>
  subject: '{{#jobs}} {{#messages}} {{message}} {{/messages}} {{/jobs}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
```

Sure you can use any other environment variable other than `env:APPVEYOR_REPO_COMMIT`. This would be more complicated if you have more than one job in matrix or/and more than one message, but still doable with more complex [mustache template](http://mustache.github.io/mustache.5.html).
