### ISSUE TITLE
AppVeyor OnPremise: Service Deployment methods not registered

### ISSUE THREAD

**Issue by itniels** [appveyor/ci#2956]
After the whole build is complete, i chose to run Webhook deployment to a demo endpoint for testing.

**Here is the entire yaml deploy part:**
```
deploy:
  provider: Webhook
  url: https://enjri1hz1j2e9.x.pipedream.net/
  request_timeout: 30
```

**But it fails with this message:**
![image](https://user-images.githubusercontent.com/15611687/58746228-24287680-845c-11e9-93cd-1169a5a89450.png)

Nothing gets sent through and the build "failed"
