### ISSUE TITLE
 WiX  on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2963]

**Comment by IlyaFinkelshteyn** [comment]
Update deploed

**Comment by csmager** [comment]
I just tried moving from VS 2017 to VS 2019 image, and I get this error:
> The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk

Is the VSIX extension installed? It's towards the bottom left of [this page](https://wixtoolset.org/releases/).

**Comment by csmager** [comment]
In case it helps anyone, I've worked around this by installing as part of the script like so:
```yaml
install:  
  - ps: $vsixPath = "$($env:USERPROFILE)\Votive2019.vsix"
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/VisualStudioExtension/releases/download/v1.0.0.3/Votive2019.vsix', $vsixPath)
  - ps: Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" "/q /a $vsixPath" -Wait
```
Should I log as a new issue?
