### ISSUE TITLE
`msbuild` failed with exit code: 1

### ISSUE THREAD

**Issue by hovancik** [appveyor/ci#2977]
Node: 12.0.0

Job: https://ci.appveyor.com/project/hovancik/stretchly/build/job/8ia5pqf7a4l08bii 

```
build: off

os: unstable

platform:
  - x86
  - x64

skip_tags: true

environment:
  nodejs_version: "12.0.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install
  - npm install -g istanbul

test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha

after_test:
  - bash <(curl -s https://codecov.io/bash)
```

repo: https://github.com/hovancik/stretchly

Everything was working fine before node 12
