### ISSUE TITLE
NSIS 3.04 on Visual Studio 2019

### ISSUE THREAD

**Issue by mikejsavage** [appveyor/ci#3019]
At the bottom of https://ci.appveyor.com/project/mikejsavage/forksow-launcher/builds/25789573

```
"C:\Program Files (x86)\NSIS\makensis.exe" -DONLY_WRITE_UNINSTALLER installer\installer.nsi
The system cannot find the path specified.
```

appveyor.yml looks like this:

```yaml
version: "{build}"
clone_depth: 1
image: Visual Studio 2019

build_script:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
- scripts\lua.exe make.lua release > build.ninja
- scripts\ninja.exe -v -k 0
- scripts\ducible.exe release\cocainediesel.exe
- scripts\ducible.exe release\elevate_for_update.exe
- scripts\ducible.exe release\headlessupdater.exe
- '"C:\Program Files (x86)\NSIS\makensis.exe" -DONLY_WRITE_UNINSTALLER installer\installer.nsi'
- installer\CocaineDieselInstaller.exe /S
- '"C:\Program Files (x86)\NSIS\makensis.exe" installer\installer.nsi'

artifacts:
- path: installer/CocaineDieselInstaller.exe
- path: release
  name: launcher_windows
```

It doesn't work if you do just `makensis.exe` without the full path either, and looking at [vs2019.json](https://github.com/appveyor/build-images/blob/master/vs2019.json) it appears that NSIS does not get installed
