### ISSUE TITLE
[BUG] appveyor-tools\secure-file thinks secret passphrase is missing

### ISSUE THREAD

**Issue by oliver-leung** [appveyor/ci#3029]
On [this build](https://ci.appveyor.com/project/HannahSi/aguaclara/builds/25994705/job/ecbkxjb05e24i3v5), I get the following error on lines 17-18:

```bash
appveyor-tools\secure-file -decrypt CI/.onshapepy.enc -secret %my_secret%
Error: Secret passphrase is missing.
```

However, the secret passphrase is clearly declared in lines 1-4 of our [`appveyor.yml`](https://github.com/AguaClara/aguaclara/blob/ec4fac0f51e174979db956d8a86c57a2b44214b4/appveyor.yml):

```yaml

environment:

  my_secret:
    secure: evqJX31ka4zt+r8BVgqL2rRbWBUzBIWODB851pQczFWKeuohT7osgD/s+H1QQ8Ef
```

Why might this be happening, and what can I do to avoid this in the future? I believe that this is similar to #2279.
