### ISSUE TITLE
OpenCover installed by Chocolately no longer in Path

### ISSUE THREAD

**Issue by Turnerj** [appveyor/ci#3047]
In the last 7 days, something has changed when running builds on [MongoFramework](https://github.com/TurnerSoftware/MongoFramework) where an application I've installed via Chocolately can no longer be accessed by a Powershell script.

Actual error message:
```
OpenCover.Console.exe : The term 'OpenCover.Console.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\projects\mongoframework\build.ps1:38 char:2
+     OpenCover.Console.exe -register:user -target:"%LocalAppData%\Micr ...
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OpenCover.Console.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 ```

[Here is a build 7 days ago where everything works fine.](https://ci.appveyor.com/project/Turnerj/mongoframework/builds/26291850)
[Here is the same commit built today where it fails.](https://ci.appveyor.com/project/Turnerj/mongoframework/builds/26454819)

The application I am running from Powershell is `OpenCover.Console.exe` and is the same version in both tests (v4.7.922). I do note that Chocolately has gone from v0.10.11 to v0.10.15 and the problem _may_ be that however I am yet to narrow it down that far. There is no error message or anything in the install process so I'm not sure if it is related.

[Here is the link to the specific line in the build script of how I call it.](https://github.com/TurnerSoftware/MongoFramework/blob/84acef2b890669065f072e66ba4bbe47462c8fd6/build.ps1#L38)

Below is a snippet of [my YML file](https://github.com/TurnerSoftware/MongoFramework/blob/84acef2b890669065f072e66ba4bbe47462c8fd6/.appveyor.yml) covering the most important parts:
```yml
version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true

services:
  - mongodb
install:
  - choco install opencover codecov
  - ps: .\build\dotnet-install.ps1 -Version 3.0.100-preview5-011568

build_script:
  - ps: .\build.appveyor.ps1 -IsTagBuild ([System.Convert]::ToBoolean($env:APPVEYOR_REPO_TAG))
```

I'm raising this as an issue just in case something else has potentially changed with the running of Powershell scripts.
