### ISSUE TITLE
Add publishing NuGet packages to GitHub Package Registry (GPR)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3104]
Original request: https://help.appveyor.com/discussions/questions/41971-push-nuget-to-github-package-registry

**Comment by Turnerj** [comment]
While I see the "Environments" section get the new "Username" field, is that field available through the YML configuration? https://www.appveyor.com/docs/deployment/nuget/

ie.

```yml
  - provider: NuGet
    server: https://nuget.pkg.github.com/MY_GITHUB_USERNAME/index.json
    artifact: /.nupkg/
    username: MY_GITHUB_USERNAME
    api_key:
      secure: ENCRYPTED_PERSONAL_TOKEN
    on:
      APPVEYOR_REPO_TAG: true
```
