### ISSUE TITLE
Enable long path names

### ISSUE THREAD

**Issue by shellshocked2003** [appveyor/ci#3129]
Hi,

I'm trying to enable long path names on Windows builds, but the change to the registry doesn't seem to be effective. Here's the config script I'm using, where the relevant portion for enabling long paths is in the `install` section:

```
build: false

environment:   
    PYTHON_HOME: "C:\\Python37"

    CONAN_REMOTES: "https://api.bintray.com/conan/conan-community/conan,https://api.bintray.com/conan/bincrafters/public-conan,https://api.bintray.com/conan/vthiery/conan-packages"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release

install:
    - ps: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10

build_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user
test_script:
  - python build.py
```

Based on [this issue](https://github.com/appveyor/ci/issues/204) it seems like reboots are possible, but I'm not sure why enabling long paths doesn't work. Is it possible to do this or what would be an alternative solution?

Thanks for your help!

**Comment by FeodorFitsner** [comment]
Is there any test one can use to check if long paths are enabled? Have you tried [logging via RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) and trying to do the same via Registry or [gpedit.msc](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/)?

**Comment by shellshocked2003** [comment]
Thanks for the quick response! Here's a link to a [repository](https://github.com/shellshocked2003/testWindowsAppveyorPath) that tests whether long paths are enabled. It simply creates a really deep directory structure, then tries to write a file with a long name there.

I've noticed with the above mentioned repository and the original one that this post is about that the build tends to freeze almost all the time when trying to enable long paths and restart. I've left the [current build](https://ci.appveyor.com/project/shellshocked2003/testwindowsappveyorpath) to run, which you can see gets stuck.

**Comment by FeodorFitsner** [comment]
Can you try doing:

```
install:
    - ps: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    - ps: Start-Sleep -s 10
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10
```
