### ISSUE TITLE
Add support for version_prefix csproj patching

### ISSUE THREAD

**Issue by jeff-winn** [appveyor/ci#3138]
The new csproj format along with the dotnet CLI have added improved semantic versioning support for version suffixes.

The command line:
```
dotnet build My.sln --version-suffix "preview"
```

With the csproj containing:
```
<PropertyGroup>
  <VersionPrefix>1.0.0</VersionPrefix>
</PropertyGroup>
```

Enables the output of a project with the semantic version of "1.0.0-preview" while keeping the assembly version, file version, etc in the correct format. As of right now your dotnet_csproj patching mechanism does not seem to recognize this setting.

I would like to propose adding support for the following within the YAML file:
```
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version_prefix: '{version}'
```

Thank you for your consideration!
