### ISSUE TITLE
None of the stack initialization is working on self-hosted AppVeyor and local Docker

### ISSUE THREAD

**Issue by belidzs** [appveyor/ci#3179]
## Build definition

```yaml
build_cloud: Docker
image: Linux
stack: python 3.7
build: off
build_script:
  - python --version
```

## Output
It produces this output:
```
Job started
git clone -q --branch=appveyor https://redacted/redacted.git /appveyor/projects/redacted
git checkout -qf redacted
Configuring 'stack'
Enabling Python 3.7.4
/opt/appveyor/build-agent/bash-shell.sh: line 62: /home/appveyor/venv3.7.4/bin/activate: No such file or directory
Error enabling 'python' stack: Command exited with code 1
```

## Environment
* Windows 10 Enterprise
* 10.0.18362 
* AppVeyor 7.0.2417 Team Edition
* Docker Desktop 2.1.0.4 (39773)
* Cloud is Docker, Linux is appveyor/build-image:minimal-ubuntu-18.04 (left at default)

I have a feeling that I might be missing something obvious, but I can't figure it out.
