### ISSUE TITLE
Github Deploy Prerelease via Environment flag

### ISSUE THREAD

**Issue by julianxhokaxhiu** [appveyor/ci#3220]
Hi,

I'm trying to implement a nightly workflow in one of my projects using your CI and at the current stage I'm able to successfully differentiate between "tag" builds, and normal pushes to master ( which will trigger a nightly build ).

At the moment though I would need to differentiate the builds between latest release and prerelease, by setting the flag. On your documentation I've read that you can just set it, although it would be nice if you could read environment variables to allow us set it via them.

For instance, see this example:
```yaml
# ...

init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME) {
        # ...
      } else {
        $env:APPVEYOR_REPO_TAG_NAME = "nightly"
        $env:IS_BUILD_NIGHTLY = "true"
      }

deploy:
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: v${appveyor_build_version}
    artifact: v${appveyor_build_version}
    pre-release: ${is_build_nightly}
    auth_token:
      secure: MY_SECURE_TOKEN
    on:
      branch: master
```

My proposal is therefore to use generic Environment variable replacement syntax, like you allow already on the "tag" key, for example.

Thank you in advance,
Julian
