### ISSUE TITLE
.snupkg packages are not pushed to artifacts automatically in Linux/macOS builds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3224]
With the following configuration `.snupkg` files must be pushed to artifacts automatically:

```
build:
  project: SomeSolution.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
```
