### ISSUE TITLE
Allow branch filtering in matrix specialising builds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3298]
Given the following config AppVeyor should start new builds on `master` branch only:

```yaml
branches:
  only:
  - master

environment:    
  matrix:
  - job_name: A
    job_group: tests

  - job_name: B
    job_group: tests

  - job_name: C
    job_group: tests

matrix:
  fast_finish: true
  
for:
  -
    matrix:
      only:
        - job_name: A

    build: off  
    test_script:
      - echo Test A
  -
    matrix:
      only:
        - job_name: B

    build: off  
    test_script:
      - echo Test B
  -
    matrix:
      only:
        - job_name: B

    build: off  
    test_script:
      - echo Test B
```

The change in the default behavior is that if all configs under `for` section have `matrix.only` or `matrix.except` then commit branch filtering applies to branches defined in "base" (top) config.
