### ISSUE TITLE
.NET 5

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3314]
Please install on preview VMs (5.0.x Runtime): https://github.com/dotnet/core-sdk

**Comment by FeodorFitsner** [comment]
Is there some official announcement/whatnew for that release?

**Comment by VladislavAntonyuk** [comment]
It was an alpha version a few weeks ago but now it is a preview1 version

**Comment by Wasapl** [comment]
I'm trying to install .Net Core 5 on linux and cant find deb packages it depends on (dotnet-runtime-5.0, aspnetcore-runtime-5.0, etc). 
@VladislavAntonyuk maybe you know how to get it?

**Comment by VladislavAntonyuk** [comment]
@Wasapi https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-x64.deb

**Comment by Wasapl** [comment]
You might notice there is a Reference note #1 for linux x64 deb packages, which states that one should install dependencies first. Do you know where to download those dependencies from?

**Comment by VladislavAntonyuk** [comment]
use tar.gz
![image](https://user-images.githubusercontent.com/33021114/74936494-e953dd80-53f2-11ea-9b83-4260511b46ff.png)

**Comment by VladislavAntonyuk** [comment]
@Wasapl I have found better way: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#examples

**Comment by Wasapl** [comment]
Oh, I saw it before. It's a bit tough to use since it does not provide a list of available channels/versions. It took me some efforts to understand that one must provide branch name in lower case:
`./dotnet-install.sh -c master` works
`./dotnet-install.sh -c Master` does not

**Comment by SimonCropp** [comment]
what i have been using 

```
image:
- macos
- Visual Studio 2019 Preview
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    install:
      - ps: >-
          Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1

          ./dotnet-install.ps1 --Version 5.0.100-preview.8.20417.9 -InstallDir 'C:\Program Files\dotnet'
  -
    matrix:
      only:
        - image: macos
    install:
      - appveyor DownloadFile https://dot.net/v1/dotnet-install.sh
      - bash dotnet-install.sh --version 5.0.100-preview.8.20417.9
      - sudo mkdir /Users/appveyor/.local/share/NuGet
      - sudo chmod a+rwx /Users/appveyor/.local/share/NuGet
build_script:
  - dotnet build src --configuration Release
  - dotnet test src --configuration Release --no-build --no-restore
test: off
```

**Comment by RehanSaeed** [comment]
This is what works for me on Windows and Ubuntu. The install of the .NET SDK seems to also work on MacOS but when I run `dotnet tool restore`, I get the error: `Command exited with code 132`.

Installing the .NET SDK on Mac OS used to work for me when the installation directory was `/Users/appveyor/.dotnet` but has stopped working since it's changed to `/usr/local/share/dotnet`.

```
# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

image:
- macOS
- Ubuntu
- Visual Studio 2019

environment:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Set the build number in MinVer.
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%

build_script:
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
- pwsh: dotnet --list-sdks
- pwsh: |
    if ($isWindows) {
      Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
      ./dotnet-install.ps1 -JSonFile global.json -InstallDir 'C:\Program Files\dotnet'
    }
    else {
      Invoke-WebRequest "https://dot.net/v1/dotnet-install.sh" -OutFile "./dotnet-install.sh"
      sudo chmod u+x dotnet-install.sh
      if ($isMacOS) {
        sudo ./dotnet-install.sh --jsonfile global.json --install-dir '/usr/local/share/dotnet'
      } else {
        sudo ./dotnet-install.sh --jsonfile global.json --install-dir '/usr/share/dotnet'
      }
    }
- pwsh: dotnet --list-sdks
- pwsh: dotnet tool restore --verbosity diagnostic
- pwsh: dotnet cake --target=Build
- pwsh: dotnet cake --target=Test
- pwsh: dotnet cake --target=Pack

test: off

artifacts:
- name: NuGet Packages
  path: ./Artefacts/**/*.nupkg
- name: NuGet Symbol Packages
  path: ./Artefacts/**/*.snupkg
- name: xUnit XML Test Results
  path: ./Artefacts/**/*.xml
- name: xUnit HTML Test Results
  path: ./Artefacts/**/*.html
- name: Code Coverage
  path: ./Artefacts/**/*.cobertura.xml
```
