### ISSUE TITLE
Set custom name for Image

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3354]
I set image with the same name as environment (Visual Studio 2019, macOS, etc) when I use matrix, so it is not possible to build the same build multiple times on the same environment . 

My proposal:
Set custom image and link it to the environment
MyBuild1: Visual Studio 2019
MyBuild2: macOS
MyBuild3: Visual Studio 2019

```
buildName:
- MyBuild1
- MyBuild2

for:
  -
    matrix:
      only:
        - buildName: My Build 1
    environment:
      OUTPUT_PLATFORM: Windows
      IMAGE: Visual Studio 2019

    build_script:
      - pwsh: >-
          # run script
    artifacts:
      - path: output
        name: Build1

  -
    matrix:
      only:
        - BuildName: MyBuild2
    environment:
      IMAGE: Visual Studio 2019
    build_script:
      - pwsh: >-
         # run script 2
    artifacts:
      - path: output
        name: Build2

```

Or

```
buildName:
- MyBuild1: Visual Studio 2019
- MyBuild2: Visual Studio 2019

for:
  -
    matrix:
      only:
        - buildName: MyBuild1

    build_script:
      - pwsh: >-
          # run script
    artifacts:
      - path: output
        name: Build1

  -
    matrix:
      only:
        - BuildName: MyBuild2
    build_script:
      - pwsh: >-
         # run script 2
    artifacts:
      - path: output
        name: Build2

```

**Comment by FeodorFitsner** [comment]
You can have something like:

```yaml
environment:
  matrix:

  - buildName: MyBuild1
    appveyor_build_worker_image: Visual Studio 2019

  - buildName: MyBuild2
    appveyor_build_worker_image: Visual Studio 2019

for:
  -
    matrix:
      only:
        - buildName: MyBuild1

    build_script:
      - pwsh: >-
          # run script
    artifacts:
      - path: output
        name: Build1

  -
    matrix:
      only:
        - BuildName: MyBuild2
    build_script:
      - pwsh: >-
         # run script 2
    artifacts:
      - path: output
        name: Build2
```
