### ISSUE TITLE
Random build failures on macOS, returning 'Build exited with code 1'

### ISSUE THREAD

**Issue by joerick** [appveyor/ci#3376]
Hi there, 

Over at https://github.com/joerick/cibuildwheel we are regularly getting random macOS build failures, that all look like this:

https://ci.appveyor.com/project/joerick/cibuildwheel/builds/31984928/job/1ftqqmjx2gxj7p4q

Specifically, they all start to install dependencies with `pip`, and then very quickly exit, with the message `Build exited with code 1`.

If this were a `pip` or a network failure, I'd expect to see log messages detailing what went wrong... instead, the build just seems to.... die. 

This is happening to ~50% of our macOS Appveyor builds at the moment.

Thanks!

Here's our config YAML:

```yaml
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"

stack: python 3.7

build: off

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install --retries 3 -r requirements-dev.txt

# the '-u' flag is required so the output is in the correct order.
# See https://github.com/joerick/cibuildwheel/pull/24 for more info.
test_script: python -u ./bin/run_tests.py

branches:
  only:
    - master

skip_commits:
  files:
    - docs/*
```

**Comment by FeodorFitsner** [comment]
Try adding `APPVEYOR_CONSOLE_DISABLE_PTY: true` environment variable, like:

```yaml
environment:
  APPVEYOR_CONSOLE_DISABLE_PTY: true

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"

...
```
