### ISSUE TITLE
OpenSSH Server is not installed on Ubuntu Hyper-V images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3384]
As a result SSH connectivity to build VM is currently broken.

Workaround:

```
init:
- sudo apt-get install -y openssh-server
```

**Comment by HariSekhon** [comment]
Could this be included in the `https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh` script?

Ie. detect if not installed and install it before enabling?

**Comment by HariSekhon** [comment]
I just worked around this like so, which fixed my build:

```
on_finish:
  # set this in Settings -> Environment dynamically instead of here
  #- sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/HariSekhon/DevOps-Bash-tools/master/setup/install_openssh.sh' | bash -e -
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
```
