### ISSUE TITLE
Bogus Windows hosts file entry for host.docker.internal

### ISSUE THREAD

**Issue by gitfool** [appveyor/ci#3415]
Discovered while working on https://github.com/mariotoffia/FluentDocker/pull/159.

`appveyor.yml` (extract):
```yml
image: Visual Studio 2019

install:
  - ps: ipconfig /all
  - ps: cat C:\Windows\System32\drivers\etc\hosts
  # - ps: ping -n 3 host.docker.internal
  - ps: docker version
  - ps: Switch-DockerLinux
  - ps: ipconfig /all
  - ps: cat C:\Windows\System32\drivers\etc\hosts
  # - ps: ping -n 3 host.docker.internal
  - ps: docker version
  - ps: docker run -it --rm busybox ifconfig
  - ps: docker run -it --rm busybox cat /etc/hosts
  - ps: docker run -it --rm busybox cat /etc/resolv.conf
  - ps: docker run -it --rm busybox ping -c 3 host.docker.internal
  - ps: docker run -it --rm busybox ping -c 3 docker.for.win.localhost
```
The [build log](https://ci.appveyor.com/project/mariotoffia/fluentdocker/builds/32607589) shows the following entries in `C:\Windows\System32\drivers\etc\hosts` (extract):
```
10.118.232.3 host.docker.internal
10.118.232.3 gateway.docker.internal
# Added by Docker Desktop
10.0.0.4 host.docker.internal
10.0.0.4 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```
Note that there are _two_ entries for `host.docker.internal` and that the first entry, `10.118.232.3`, is bogus; `ping -n 3 host.docker.internal` from on the host will fail! It should only contain the second entry, `10.0.0.4`, which matches the ethernet adapter address as seen from `ipconfig` (extract):
```
Ethernet adapter Ethernet 4:
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #4
   Physical Address. . . . . . . . . : 00-15-5D-A4-60-56
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::11a9:3db3:e73f:fefb%15(Preferred) 
   IPv4 Address. . . . . . . . . . . : 10.0.0.4(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.0.1
   DHCPv6 IAID . . . . . . . . . . . : 251663709
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-25-34-46-E2-00-15-5D-A4-36-3C
   DNS Servers . . . . . . . . . . . : 8.8.8.8
                                       1.1.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
