### ISSUE TITLE
No Python shared libraries on macOS

### ISSUE THREAD

**Issue by KmolYuan** [appveyor/ci#3423]
Environment: virtualenv (`~/venv3.x.x`) on macOS images.

The packing module PyInstaller cannot found the shared libraries.

```bash
OSError: Python library not found: .Python, libpython3.7.dylib, Python, libpython3.7m.dylib
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.
    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

I'm not sure `--enable-shared` is passed when building them.
Re-installed from source will solve this problem.

```yml
- sh: '[[ "$(uname)" == "Linux" ]] && source ~/venv${PY}/bin/activate || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && brew update || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && brew install pyenv || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && export PATH=~/.pyenv/shims:${PATH} || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${PY} || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && pyenv global ${PY} || true'
- sh: '[[ "$(uname)" == "Darwin" ]] && pyenv rehash || true'
```

My builds: https://ci.appveyor.com/project/KmolYuan/pyslvs-ui/builds/32786942
Re-build version: https://ci.appveyor.com/project/KmolYuan/pyslvs-ui/builds/32791502
