### ISSUE TITLE
The Unicode environment variables were displayed incorrectly in `install` and `build` sections

### ISSUE THREAD

**Issue by sih4sing5hong5** [appveyor/ci#3485]
### 1. Summary
The Unicode environment variables were displayed incorrectly in `install` and `build` sections, but correctly in `init` sections. Other scripts cannot import them.

### 2. Related Issues
- https://github.com/appveyor/ci/issues/2226

### 3. Configuration
The [build](https://ci.appveyor.com/project/sih4sing5hong5/appveyor-unicode/builds/34103593)
```
version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  APP_NAME: 漢字 kah Lô-má-jī

init:
  - ps: echo "== init =="
  - ps: chcp
  - ps: echo "${env:APP_NAME}"
  - ps: chcp 65001
  - ps: echo "${env:APP_NAME}"

install:
  - ps: echo "== install =="
  - ps: chcp
  - ps: echo "${env:APP_NAME}"
  - ps: chcp 65001
  - ps: echo "${env:APP_NAME}"

build_script:
  - ps: echo "== build_script =="
  - ps: chcp
  - ps: echo "${env:APP_NAME}"
  - ps: chcp 65001
  - ps: echo "${env:APP_NAME}"
```

### 4. Expected behavior
```
Build started
echo "== init =="
== init ==
chcp
Active code page: 437
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
git clone -q --branch=master https://github.com/i3thuan5/Appveyor_Unicode.git C:\projects\appveyor-unicode
git checkout -qf eed415f1e6c976afa93e4e2fc5b6c7a6ac4f794f
Running Install scripts
echo "== install =="
== install ==
chcp
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
echo "== build_script =="
== build_script ==
chcp
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
Discovering tests...OK
Build success
```

### 5. Actual behavior
The string `漢字 kah Lô-má-jī` displayed incorrectly in `install` and `build_scripts` sections. It became `Ã¦Â¼Â¢Ã¥Â­â€” kah LÃƒÂ´-mÃƒÂ¡-jÃ„Â«`.

```
Build started
echo "== init =="
== init ==
chcp
Active code page: 437
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
git clone -q --branch=master https://github.com/i3thuan5/Appveyor_Unicode.git C:\projects\appveyor-unicode
git checkout -qf eed415f1e6c976afa93e4e2fc5b6c7a6ac4f794f
Running Install scripts
echo "== install =="
== install ==
chcp
Active code page: 65001
echo "${env:APP_NAME}"
Ã¦Â¼Â¢Ã¥Â­â€” kah LÃƒÂ´-mÃƒÂ¡-jÃ„Â«
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
Ã¦Â¼Â¢Ã¥Â­â€” kah LÃƒÂ´-mÃƒÂ¡-jÃ„Â«
echo "== build_script =="
== build_script ==
chcp
Active code page: 65001
echo "${env:APP_NAME}"
Ã¦Â¼Â¢Ã¥Â­â€” kah LÃƒÂ´-mÃƒÂ¡-jÃ„Â«
chcp 65001
Active code page: 65001
echo "${env:APP_NAME}"
Ã¦Â¼Â¢Ã¥Â­â€” kah LÃƒÂ´-mÃƒÂ¡-jÃ„Â«
Discovering tests...OK
Build success
```
