### ISSUE TITLE
 Windows cmd mode pollute the env variables containing non-ASCII

### ISSUE THREAD

**Issue by sih4sing5hong5** [appveyor/ci#3487]
### 1. Summary
After running commands in Windows Command, the env variables containing  non-ASCII chars didn't work.

##### Related issues
#3485 

### 2. Configuration
The [build](https://ci.appveyor.com/project/sih4sing5hong5/appveyor-unicode/builds/34122261#L3)
```
version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  APP_NAME: 漢字 kah Lô-má-jī

init:
  - ps: echo "== init =="
  - ps: echo "${env:APP_NAME}"
  - echo "${env:APP_NAME}"
  - ps: echo "${env:APP_NAME}"

build_script:
  - ps: echo "== build_script =="
  - ps: echo "${env:APP_NAME}"
```

### 3. Excepted Behavior
```
Build started
echo "== init =="
== init ==
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
echo "${env:APP_NAME}"
"${env:APP_NAME}"
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
git clone -q --branch=windows-cmd https://github.com/i3thuan5/Appveyor_Unicode.git C:\projects\appveyor-unicode
git checkout -qf b4999de48184644bee5c61e0639f07adb15a550c
...
```

### 4. Actual Behavior
It should output `漢字 kah Lô-má-jī` instead of `?? kah L“-m -ji`
```
Build started
echo "== init =="
== init ==
echo "${env:APP_NAME}"
漢字 kah Lô-má-jī
echo "${env:APP_NAME}"
"${env:APP_NAME}"
echo "${env:APP_NAME}"
?? kah L“-m -ji
git clone -q --branch=windows-cmd https://github.com/i3thuan5/Appveyor_Unicode.git C:\projects\appveyor-unicode
git checkout -qf b4999de48184644bee5c61e0639f07adb15a550c
...
```
