### ISSUE TITLE
Environment variable in deploy.release is case-sensitive on MacOS

### ISSUE THREAD

**Issue by shrinktofit** [appveyor/ci#3505]
An example as shown in https://www.appveyor.com/docs/deployment/github/:
```yaml
deploy:
  release: myproduct-v$(appveyor_build_version)
  provider: GitHub
```

This will create a GitHub release with name "myproduct-v$(appveyor_build_version)" on MacOS, without substitution.
