### ISSUE TITLE
macOS 10.14 vnc failed

### ISSUE THREAD

**Issue by gengjiawen** [appveyor/ci#3509]
config:
```yml
image: macos-mojave

install:
  - node -p "process.cwd()"
  - npx envinfo

on_finish:
  - sh: export APPVEYOR_VNC_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
  
test: off
```

log, from https://ci.appveyor.com/project/gengjiawen/appveyor-playground/builds/34653813

```console
Running "on_finish" scripts
export APPVEYOR_VNC_BLOCK=true
curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
Data source (.) is not valid.
Failed to change user's password! Aborting
Command exited with code 1
Build failed
```
