### ISSUE TITLE
Support for .NET 5.0 / .NET 5.0-Windows (Preview 8) in Windows Image

### ISSUE THREAD

**Issue by BornToBeRoot** [appveyor/ci#3522]
.NET 5.0 build are currently failing with "Invalid target framework 'unsupported'"

Add .NET 5.0 support to Windows Image.

.NET 5.0 Preview 8 is now feature complete. There will be 2 rc, and a then the final release in November: https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-8/

SDK:
- SDK 5.0.100-preview.8 https://dotnet.microsoft.com/download/dotnet/5.0

Dependencies: 
- Visual Studio 2019 (v16.8, Preview 2)

**Comment by FeodorFitsner** [comment]
You can install the latest version of .NET 5.0 during the build with the following `appveyor.yml` snippet:

```yaml
install:
- ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
- ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -Version "5.0.100-preview.8.20417.9" -InstallDir "$env:ProgramFiles\dotnet"'
```
