### ISSUE TITLE
.NET Core 3.1.9

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#3548]
GDay 👋🏻 

Could we please get version 3.1.9 installed into the base image?

When creating nuget packages, it's recommended to have version 3.1.400 for "compiler flags" setting, please?

**Comment by FeodorFitsner** [comment]
Right now `Visual Studio 2019` image has SDK 3.1.402. Is that enough?

**Comment by PureKrome** [comment]
<Pirate voice> Argh!!!! </Pirate voice>

I should have specified for the `Ubuntu` image. My bad. soz.

**Comment by FeodorFitsner** [comment]
OK, the best way to have the latest .NET Core on Linux is adding this to `appveyor.yml`:

```yaml
environment:
  CORE_SDK_LINUX_URL: https://download.visualstudio.microsoft.com/download/pr/fdd9ecec-56b4-40f4-b762-d7efe24fc3cd/ffef51844c92afa6714528e10609a30f/dotnet-sdk-3.1.403-linux-x64.tar.gz

install:
  - sh: wget -O dotnet-sdk.tar.gz ${CORE_SDK_LINUX_URL}
  - sh: sudo tar zxf dotnet-sdk.tar.gz -C /usr/share/dotnet
```
