### ISSUE TITLE
 node x64 package not found (node-v15.x)

### ISSUE THREAD

**Issue by hyj1991** [appveyor/ci#3563]
Hi,

I configured a matrix-job on several nodejs-versions, but the node-v15.x are constantly running into "package not found"-errors. All the other nodejs-versions are resulting green.

This is my config-fille:

```yml
# use x86_64, default is ia32
platform:
  - x64

# Test against the latest version of this Node.js version
environment:
  matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"
    - nodejs_version: "15"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run ci
  - npm run ci

# Don't actually build.
build: off
```

And the error shows:

![image](https://user-images.githubusercontent.com/19908330/98752587-71ed3080-23fd-11eb-946d-20d5646cd65a.png)

Cheers!
