### ISSUE TITLE
[QUESTION] Package artifact from two jobs in one

### ISSUE THREAD

**Issue by S0PEX** [appveyor/ci#3577]
Hey,

I am currently building a multi-project solution in VS17. The project has a x64 and x86 target and I would like to push a combined artifact to my github released. After some trial and error I haven't found a way to include the x64 and x86 build files in one zip. I have tried cashes and so on. The only solution that worked was to create my own build script inside my project that just runs msbuild with x64 and x86 and is shown as one job. Is there a way to merge the artifacts of two jobs or run two jobs and share the build folder ?

Regards Artur

**Comment by FeodorFitsner** [comment]
Your own script doing both x64 and x86 in the same build is a good solution imho.

**Comment by S0PEX** [comment]
Is there any way that I could keep the default build jobs and add a custom job that runs after the x64 and x86 default builds have finished ? When I tried to add a custom job to the matrix config the default jobs got disabled.

**Comment by FeodorFitsner** [comment]
Yes, you can: https://www.appveyor.com/docs/job-workflows/

Example `appveyor.yml` where tests for Windows, Linux and macOS are run in parallel and after that there is a "releasing" job: https://github.com/pglet/pglet/blob/ui-p1/.appveyor.yml

**Comment by S0PEX** [comment]
Thanks for the answer but its it configuring everything in the example by hand ?
Currently my .appveyor.xml looks like this 
```yml
image: Visual Studio 2019

platform: 
  - x86
  - x64
 
configuration: Release

before_build:
  - findstr /V "{48C5258A-FA49-4173-AEE5-0FCA5190DFF2}.Debug {48C5258A-FA49-4173-AEE5-0FCA5190DFF2}.Release" .\ReClass.NET.sln > cleaned.sln # This removes the .Unix project from the solution another option would be to create a custom target inside the project
  - rm ReClass.NET.sln
  - nuget restore # restore nuget dependencies

# Build the solution with the name cleaned.sln
build:
  project: cleaned.sln
  verbosity: minimal

# Package the builded files into a zip and push as artifacts
after_build:
  - cd %APPVEYOR_BUILD_FOLDER% # CD into the cloned project folder
  - cd Bin # CD into  Bin
  - cd Release # CD into Release
  - set BUILD_ARCHIVE=%APPVEYOR_PROJECT_NAME%-%CONFIGURATION%-%PLATFORM%.zip # Set our output archive as projectname-(Debug|Release)-(x86|x64)
  - cmd: 7z a -r %BUILD_ARCHIVE% *.dll *.exe # Add all exe and dll files to our archive
  - appveyor PushArtifact %BUILD_ARCHIVE% # Upload the archive as an artifact
```

Once I add a custom job matrix the default x86 and x64 release and test jobs are gone.
