### ISSUE TITLE
Support Node.js 14.16.0

### ISSUE THREAD

**Issue by hovancik** [appveyor/ci#3647]
```
Build started
git clone -q --branch=release https://github.com/hovancik/stretchly.git C:\projects\stretchly
git checkout -qf 0a9cc4fd857a08fc78991e94fd311bfe092b8470
Running Install scripts
Install-Product node $env:nodejs_version
node  x86 package not found
```

```
os: Visual Studio 2019

platform:
  - x64

skip_tags: true

environment:
  nodejs_version: "14.16.0"

branches:
  only:
    - release

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install

build_script:
  - node_modules/.bin/electron-builder build --x64 --ia32
```
