### ISSUE TITLE
Mysql service giving SSL Connection Error

### ISSUE THREAD

**Issue by Jaxelr** [appveyor/ci#3696]
While using the service of mysql, ive stumble upon this error on builds that were working last week (no changes to code made):

```log
   MySql.Data.MySqlClient.MySqlException : SSL Connection error.
---- System.AggregateException : One or more errors occurred. (Cannot determine the frame size or a corrupted frame was received.)
```
Ive included a sample yaml used to repro:

```yaml
version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration:
  - Release
services:
  - mysql
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test .
```

Here's a sample build: https://ci.appveyor.com/project/Jaxelr/appveyortest
Using the following github code: https://github.com/Jaxelr/AppveyorTest
