### ISSUE TITLE
TLS error when downloading Rust crates

### ISSUE THREAD

**Issue by KizzyCode** [appveyor/ci#3701]
When I try to build my project [https://github.com/KizzyCode/serde_dynamic_typing-rust](https://github.com/KizzyCode/serde_dynamic_typing-rust), AppVeyor fails to download the associated crates from crates.io:
```
[35] SSL connect error (schannel: initial InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.)
```
(Full build output here [https://ci.appveyor.com/project/KizzyCode/serde-dynamic-typing-rust/build/job/ujk9sygik07wl5ej](https://ci.appveyor.com/project/KizzyCode/serde-dynamic-typing-rust/build/job/ujk9sygik07wl5ej))

My `.appveyor.yml` is:
```
environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-toolchain nightly --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build: false

test_script:
  - cargo +nightly test --verbose
  - cargo +nightly test --verbose --release
```

I was unable to reproduce this error on my Windows test systems.
