### ISSUE TITLE
Filtering out all jobs with conditional build configuration creates hanging build (Queued)

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [appveyor/ci#3753]
### Tested with

  - ci.appveyor.com + github.com
  - AppVeyor OnPrem `v7.0.2942` + Gitea `1.15.6`

### Issue Description

When filtering with conditional build configuration with e.g. `branch/only` or `skip_commits` and the commit condition results in filtering all possible jobs, appveyor creates a I would say empty build which is hanging in status 'Queued'. See hanging build examples:

- [Jobs filtered due to `branch/only`](https://ci.appveyor.com/project/DoLearnWhileAlive/appveyor-ci-test-simple/builds/41418754)
- [Jobs filtered due to `skip_commits`](https://ci.appveyor.com/project/DoLearnWhileAlive/appveyor-ci-test-simple/builds/41418511)

#### appveyor.yml

```
image: Visual Studio 2019  

environment:
  matrix:
    - job_name: build_dev
    - job_name: build_main

build_script:
  - ps: Write-Host "Build test"

test: off 

for:
  -
    matrix:
      only:
        - job_name: build_dev

    branches:
      only:
        - dev

    skip_commits:
      message: /^Do not build commit.*/

  -
    matrix:
      only:
        - job_name: build_main

    branches:
      only:
        - main

    skip_commits:
      message: /^Do not build commit.*/
```
