### ISSUE TITLE
How to install SDK "Microsoft.WinJS.2.0, Version=1.0"?

### ISSUE THREAD

**Issue by bguiz** [appveyor/ci#377]
Building a Windows 8.1 universal app, which builds locally on an MS Surface using MSBuild 14.0.

On Appveyor I get this error:

```
error MSB3774: Could not find SDK "Microsoft.WinJS.2.0, Version=1.0". 
```

How do I tell Appveyor to install this SDK?

Relevant parts of my `appveyor.yml`:

```yaml
os: Visual Studio 2015
configuration: Release;outDir="dist"
platform: Any CPU
clone_folder: c:\projects\universal-app
build:
  project: c:\projects\universal-app\platform\windows\UniversalApp.Windows.jsproj
  verbosity: detailed
```
