### ISSUE TITLE
Miniconda version - Python 3.8+?

### ISSUE THREAD

**Issue by c-f-h** [appveyor/ci#3783]
Hi,

I'm wondering why the latest preinstalled version for miniconda seems to be that with Python 3.7 and no later Python versions are supported. For context, I use a path of the form

    MINICONDA: "C:\\Miniconda37-x64"

for my CI script, but changing that to `Miniconda38` does not work.

**Comment by duncanmmacleod** [comment]
@c-f-h, you can get around that by manually specifying a newer build image, e.g.

```yaml
image: Visual Studio 2022
environment:
  global:
    MINICONDA: C:\Miniconda38-x64
```

But it would be better to have this available by default.
