### ISSUE TITLE
"No artifacts found matching path" error for Asp.Net Core MVC Deployment to Azure App Service Linux

### ISSUE THREAD

**Issue by sahgilbert** [appveyor/ci#3852]
- I have an Asp.Net Core MVC website running .Net 6.0.
- I'm trying to deploy the website to an Azure App Service Linux Server.
- I'm getting the following error "No artifacts found matching **'.HousePlatform\HousePlatform\bin\Release\net6.0\publish'** path".
- How do I fix this error?

**Here is my folder path:**

<img width="1371" alt="Screenshot 2022-11-08 at 12 21 40" src="https://user-images.githubusercontent.com/13452745/200562521-c750f599-de25-47c7-80e8-e418370642ff.png">

**Here is the error in AppVeyor:**

<img width="786" alt="Screenshot 2022-11-08 at 12 23 28" src="https://user-images.githubusercontent.com/13452745/200562799-45630404-7035-4ebb-9a7a-5216640cf7da.png">

**Here is my appveyor.yml file:**

```
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}-{branch}

branches:
  only:
   - master
 
#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_depth: 1

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

init:
  - cmd: git config --global core.autocrlf true
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release
  
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./HousePlatform/HousePlatform.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./HousePlatform/HousePlatform.csproj

#---------------------------------#
#       test configuration       #
#---------------------------------#
test_script:
  - cmd: dotnet build ./UnitTests/UnitTests.csproj --verbosity m
  - cmd: dotnet test

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: '.HousePlatform/HousePlatform/bin/Release/net6.0/publish'
   name: WebsiteSourceCode
   type: WebDeployPackage
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
- provider: WebDeploy
  server:  [REDACTED_FOR_SECURITY]
  website:  [REDACTED_FOR_SECURITY]
  username:  [REDACTED_FOR_SECURITY]
  password:
    secure: [REDACTED_FOR_SECURITY]
  artifact: WebsiteSourceCode
  aspnet_core: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true
```

Many thanks
