### ISSUE TITLE
Could not connect to the remote computer ("website-name-here.scm.azurewebsites.net")

### ISSUE THREAD

**Issue by sahgilbert** [appveyor/ci#3853]
- I have an Asp.Net Core MVC website running .Net 6.0.
- I'm trying to deploy the website to an Azure App Service Linux Server.
- I'm getting the following error: 
"Could not connect to the remote computer ("website-name-here.scm.azurewebsites.net") On the remote computer, make sure that Web Deploy is installed and that the required process ("Web Management Service") is started.  Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_DESTINATION_NOT_REACHABLE."

<img width="956" alt="Screenshot 2022-11-08 at 13 00 38" src="https://user-images.githubusercontent.com/13452745/200583845-0aa17513-b0a1-4f38-a58b-bc2ba4c12696.png">

The Linux server is deployed and running...
How do I fix this error?

**Here is my appveyor.yml file:**

```
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}-{branch}

branches:
  only:
   - master
 
#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_depth: 1

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

init:
  - cmd: git config --global core.autocrlf true
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release
  
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./HousePlatform/HousePlatform.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./HousePlatform/HousePlatform.csproj

#---------------------------------#
#       test configuration       #
#---------------------------------#
test_script:
  - cmd: dotnet build ./UnitTests/UnitTests.csproj --verbosity m
  - cmd: dotnet test

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: '.\HousePlatform\bin\Any CPU\Release\net6.0\publish'
   name: WebsiteSourceCode
   type: WebDeployPackage
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
- provider: WebDeploy
  server: https://house-platform-dev.scm.azurewebsites.net/msdeploy.axd?site=house-platform-dev
  website: house-platform-dev
  username: $house-platform-dev
  password:
    secure: Tn4uvnR63Vzm4045D+xUnABHny9FWO4LAJnB0aLqVrDjnNHvjedQsaYO2rwHBXErbbCOFUN4LvLn0zLl1R1BLg==
  artifact: WebsiteSourceCode
  aspnet_core: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true
```

Thank you

**Comment by FeodorFitsner** [comment]
I've never tried deploying to a Linux server with WebDeploy and I'm not even sure if it's supported as WebDeploy is strictly Windows technology.
Try using Zip Push deployment instead: https://www.appveyor.com/docs/deployment/azure-app-service-zip-push-deploy/

**Comment by sahgilbert** [comment]
I've built [a demo Asp.Net MVC Core 7.0 project here](https://github.com/sahgilbert/AppVeyorLinuxDeploymentTest).

Here is the AppVeyor log output:

<img width="937" alt="Screenshot 2022-11-20 at 19 16 30" src="https://user-images.githubusercontent.com/13452745/202921618-18ea6ca6-d02c-4100-8cec-e6ca0aabd0d8.png">

Here is the Azure App Service:

<img width="1440" alt="Screenshot 2022-11-20 at 19 17 28" src="https://user-images.githubusercontent.com/13452745/202921645-7fa17162-b5df-46a7-b002-cd3f324150aa.png">

Here is the AppVeyor YAML file:

```
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}-{branch}

branches:
  only:
   - master
 
#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_depth: 1

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

init:
  - cmd: git config --global core.autocrlf true
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./AppVeyorLinuxDeploymentTest/AppVeyorLinuxDeploymentTest.csproj --verbosity m
build:
  publish_wap_xcopy: true
  parallel: true
  verbosity: detailed
build_script:
  - cmd: dotnet publish ./AppVeyorLinuxDeploymentTest/AppVeyorLinuxDeploymentTest.csproj

#---------------------------------#
#       test configuration       #
#---------------------------------#
test_script:
  - cmd: dotnet build ./UnitTests/UnitTests.csproj --verbosity m
  - cmd: dotnet test

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: '.\AppVeyorLinuxDeploymentTest\bin\Any CPU\Release\net7.0\publish'
   name: WebsiteSourceCode
   type: Zip
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
- provider: AzureAppServiceZipDeploy
  server: https://house-platform-dev.scm.azurewebsites.net:443/msdeploy.axd?site=house-platform-dev
  website: house-platform-dev
  username: $house-platform-dev
  password:
    secure: Tn4uvnR63Vzm4045D+xUnABHny9FWO4LAJnB0aLqVrDjnNHvjedQsaYO2rwHBXErbbCOFUN4LvLn0zLl1R1BLg==
  artifact: WebsiteSourceCode
  aspnet_core: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true
```

@FeodorFitsner  What have I not configured correctly in the YAML file? Thanks
