### ISSUE TITLE
node  x86 package not found

### ISSUE THREAD

**Issue by klausJensen** [appveyor/ci#3898]
Hey, 

We have an old project that have been running fine and deployed yesterday, but today fails with out any changes(rolled back to the commit that was successfully deployed yesterday. 
![image](https://github.com/appveyor/ci/assets/90904664/f5613ac0-ef33-4741-8186-6fff1f9fc9cd)

The yml looks like the following: 
```
environment:
  nodejs_version: "10.15.1"

init:
  - git config --global core.autocrlf false
  - git config --global core.longpaths true

cache:
  - packages -> **\packages.config
  
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm i npm@8.1.3 -g
  - cmd: cd Source\Frontend\ && npm install 
```
Figured it was Node 10.15.1 that was no longer availablem, so tryed with 10.24.1, and Latest, but got the same error. 
Any idea what is goin on here ?
