### ISSUE TITLE
Incorrect `clone_depth` parsing when using macos image

### ISSUE THREAD

**Issue by julien-jean** [appveyor/ci#3912]
Hello! :wave: 

We're having trouble with shallow cloning when using macos images. The `clone_depth` property do not seem to be correctly parsed.

Here's our base config (sorry for not having a reproducer):

```yaml
build: false
image: macos-sonoma # same issue on macos-monterey
shallow_clone: true
clone_depth: 6
skip_tags: true
branches:
  only:
    - staging
    - prod
```

When the pipeline starts, we can retrieve in the job output the following error message:

```
git clone -q --branch=main https://myrepo.git;6 /Users/appveyor/projects/my-workspace-79ve7
/usr/local/Cellar/appveyor-build-agent/7.0.3293/bash-shell.sh: line 51: 6: command not found
```

Looks like the `clone_depth` property isn't correctly retrieved from the yaml and is parsed as a command instead. As you can see, `6` is the `clone_depth` value.

* It's not used when cloning
* bash-shell.sh seems to execute it as command (which obviously fails)

> Also we're using appveyor from gitlab.

What can I do to fix this?
