### ISSUE TITLE
MinGW 32-bit seems missing from recent images

### ISSUE THREAD

**Issue by LeonarddeR** [appveyor/ci#3925]
On the [pre-installed software page](https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin), MinGW 32-bit is listed as installed. However, it looks like it is either not installed or not installed where advertised.

Snippet:

```yaml
install:
  - cmd: |
      cd C:\MinGW
```

This gives: `The system cannot find the path specified.`
