### ISSUE TITLE
Add support for NET9.0 in Visual Studio 2022 image

### ISSUE THREAD

**Issue by jrgcubano** [appveyor/ci#3936]
NET9 has been officially released and it would be nice to have it available to start using it with our builds and deploys.

Thanks in advance.

**Comment by jrgcubano** [comment]
@OwenMcDonnell It would be appreciated if it could also be included in the Ubuntu images. Thanks

**Comment by Jaxelr** [comment]
FYI, as a workaround I usually do this:

```yaml
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '9.0.100' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
  - cmd: dotnet --version
```

Might be unsuitable for your use case, but it might unblock you for the short term :)
