### ISSUE TITLE
Missing "auth_token" in Slack notification settings causes build to fail silently

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#398]
`auth_token` should be defined to make it work.

```
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/AAABBBCCC111
  auth_token: ''
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
```
