### ISSUE TITLE
Store some artifacts in case of failure

### ISSUE THREAD

**Issue by krlmlr** [appveyor/ci#401]
@FeodorFitsner Would you consider making artifacts available even in case of a build failure? In our case, some artifacts are log files which contain important information about the build failure. The current workaround is to print the contents of the logs, but this clutters the output.

I know I can push the artifacts manually via the API, but I think it would be much simpler to have a configuration option that allows an artifact to be published even if the build failed.

``` yml
artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
    publish_on_failure: true
```

https://github.com/krlmlr/r-appveyor/issues/37
