### ISSUE TITLE
Xamarin license activation/deactivating for PR builds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#443]
Discussion: http://help.appveyor.com/discussions/questions/1728-register-xamarin-license-for-pull-requests

**Comment by FeodorFitsner** [comment]
There is a new `Xamarin` tab on project settings that allows specifying Xamarin account credentials and enable product to register Xamarin license for.

To configure in `appveyor.yml`:

```
xamarin:
  email: your@email.com
  password:
    secure: ABC123==
  android: true
  ios: true
```
