### ISSUE TITLE
Tags filter

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#486]
Discussion: http://help.appveyor.com/discussions/suggestions/868-only-build-for-tags-that-match-a-given-pattern

**Comment by ShaneYu** [comment]
This would be a handy feature.

**Comment by bompi88** [comment]
Currently I'm using this for semantic versioning:

```yml
branches:
  only:
    - /v\d+\.\d+\.\d+((-beta.\d+)|(-\d+))?/
```
