### ISSUE TITLE
SFTP to sourceforge.net works, however, the artifact is being uploaded to a wrong location

### ISSUE THREAD

**Issue by weitjong** [appveyor/ci#491]
Below is the simplified version of the ```deploy``` section in my ```appveyor.yml``` file.
```
deploy:
  - provider: FTP
    protocol: sftp
    host: frs.sourceforge.net
    username: urho-travis-ci
    password: mypassword
    folder: $(UPLOAD_DIR)
```
The UPLOAD_DIR environment variable is set to something like: 
```
"/home/frs/project/$env:APPVEYOR_REPO_NAME/Snapshots"
```
Note that this is an absolute path. The absolute path ```/home/frs/project/***registered-project-name***/``` is provided by SF.net and has been proven to be correct in our Travis-CI setup. Given the APPVEYOR_REPO_NAME = "FOO" and artifact = "BAR.zip" then I expect the artifact should be being transfered as ```/home/frs/project/FOO/Snapshots/BAR.zip"```. However, the FTP provider seems to disregard the leading "/" in the remote folder setting and treat the path as if it is a relative path, as such the actual result is the artifact end up as ```/home/users/u/ur/urho-travis-ci/home/frs/project/FOO/Snapshots/BAR.zip```. Note the ```/home/users/u/ur/urho-travis-ci``` is the default path given to my account "urho-travis-ci" on SF.net, but we are not supposed to upload anything under the default path.
