### ISSUE TITLE
node 1.0.4 x86 package not found

### ISSUE THREAD

**Issue by matthewp** [appveyor/ci#500]
Is iojs not supported any more?  Very simple config:

```
# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  # io.js
  - nodejs_version: "1.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
```
