### ISSUE TITLE
No artifacts were published. Make sure you have specified correct artifacts filter.

### ISSUE THREAD

**Issue by colt05** [appveyor/ci#603]
Hello.
I have been having a problem releasing binaries to Github Releases on my repo 24Time-2-12Time. I have tried multiple fixes including adding the C:\projects\ (etc.) to the artifact path but it still does not work. 
Is there a fix?
Thanks.

**Comment by FeodorFitsner** [comment]
What AppVeyor project URL is that?

**Comment by colt05** [comment]
https://ci.appveyor.com/project/colt05/24time-2-12time/

**Comment by FeodorFitsner** [comment]
Just remove `artifact` setting at all.

**Comment by colt05** [comment]
Ok.

**Comment by colt05** [comment]
Ok, so I backed the old YML up and here is the commit for the new one: https://github.com/colt05/24Time-2-12Time/commit/d1065b56de6a4aa940ba95016f81c945039146f7

**Comment by FeodorFitsner** [comment]
I suggested to remove only `artifact` setting from provider, not `artifacts`. I believe correct `appveyor.yml` could be:

```
version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: 24212C-DLL.sln
  verbosity: normal
artifacts:
- path: bin/Release/24212C-DLL.dll
  name: dll
deploy:
- provider: GitHub
  description: Automatic AppVeyor Release
  auth_token:
    secure: eboRJKDEY27I443NGjyN6uMIVAbJ0bQAmwx+jmjwrJNGhptf3Se5drhsD6j330jb
  on:
    branch: master
```
