### ISSUE TITLE
Question: Is there a way to specify .runsettings without a verbose test script command?

### ISSUE THREAD

**Issue by am11** [appveyor/ci#605]
Hello,

Unfortunately, it seems like there is no way to permanently assign a default test settings file with test project in Visual Studio. So every time locally we have to select `.runsettings` via `VS > Test > Select Test Settings File`.

To run the tests on AppVeyor, I have found a way ([ref](https://github.com/csMACnz/Coveralls.net-Samples/blob/b565f09/appveyor.yml#L20)) to specify `*.runsettings`:

```yaml
test_script:
- ps: >-
vstest.console.exe /inIsolation /Enablecodecoverage`
/TestAdapterPath:".\src\packages\xunit.runner.visualstudio.2.1.0\build\_common\"`
.\tests\bin\Debug\LibSass.NET.Tests.dll /Settings:LibSass.NET.Tests.runsettings
```

Is there a better way to specify `runsettings` without transforming `test:` block to `test_script` in YAML and specifying the full (scary) command?

PS
FWIW, I only need it to specify x64 test runner (as VS defaults to x86 variant: https://github.com/am11/libsass-net/blob/8fe9b6a/LibSass.NET.Tests.runsettings; please feel free to suggest if there is a smarter alternative to permanently make 64-bit VS test runner default =)).

**Comment by FeodorFitsner** [comment]
Nope, but we could define some kind of naming convention for AppVeyor to automatically pick up `.runsettings` (like `<the_name_of_assembly>.runsettings` in the same folder). Sounds like a feature request.

**Comment by am11** [comment]
Thanks @FeodorFitsner. In addition to automatically load the `<same_name_of_test_assembly>.runsettings` from repo root (or `test/bin/{Configuration}/` directory?), it would be nice to be able to specify with path:

```yaml
test:
  # assemblies to test - optional
  assemblies:
    - test-assembly-A.dll
    - '**\*.[Tt]ests.dll'
  settings: path/to/settings.runsettings # or /path/to/settings.testsettings
  # if the glob pattern or the list is provided, only the first file would be selected
```
