### ISSUE TITLE
AWS CodeDeploy

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#633]
Resources:
http://docs.aws.amazon.com/codedeploy/latest/userguide/getting-started-windows.html
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html

**Comment by spyoungtech** [comment]
For anyone interested in this: I've rigged up a workaround for this using the an AWS S3 Environment provider, combined with an AWS lambda function that creates a CodeDeploy deployment via the S3 write event.

A basic example works as follows:

* Create a CodeDeploy application and deployment group(s)
* Create an S3 bucket to contain your appveyor CodeDeploy deployments.
* Create an AWS S3 deployment environment with the following configuration:
   * Name: `CodeDeploy`
   * (configure your S3 bucket settings based on bucket you created)
   * Folder: `$(application_name)/$(deployment_group)/$(appveyor_build_version)`
   * Artifacts: `$(artifact_name)`
* Create an AWS Lambda function
  * Here's an [example function using Python 3.6](https://gist.github.com/spyoungtech/5fa304ad21210bb9c347184dace4c508)
   * Configure an S3 trigger for `ObjectCreated` events using the bucket you created earlier
   * The IAM execution role should have S3 read and CodeDeploy access.


Your `appeyor.yml` may contain something like this.

```
after_build: 
  # package zip for codedeploy
  - 7z a myapp-codedeploy.zip path\to\assets\*.dll -ir!.\path\to\appspec.yml

artifacts:
  - path: myapp-codedeploy.zip
    name: CodeDeployBundle

deploy:
  - provider: Environment
    name: CodeDeploy
    application_name: "myapp"
    deployment_group: "myDG"
    artifact_name: "CodeDeployBundle"
```

Now when this deployment environment is triggered, it should write to S3 which, in turn, will trigger the Lambda function that kicks off the CodeDeploy deployment.

So far, this setup is working for us. Main benefit is the clean `deploy` section. The same could be achieved with scripts and AWS CLI, but this is less overhead for devs to think about, in my view.
