### ISSUE TITLE
node x86/x64 package not found

### ISSUE THREAD

**Issue by jaumard** [appveyor/ci#729]
I follow this doc : http://www.appveyor.com/docs/lang/nodejs-iojs

but I have this error : 
```
Running Install scripts
[00:00:03] Install-Product node $env:nodejs_version
[00:00:04] node  x86 package not found
```

Here is my appveyor.xml : 
```
# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "4.4.2"
  - nodejs_version: "5.1.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

platform:
  - x86
  - x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
```

Why it doesn't find/install node ? Also is there a way to have stable LTS and stable version of Node instead of hard coding the version ?
