### ISSUE TITLE
GET support in Webhook notifications and variables in URL and headers

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#751]
You can now choose between `GET` and `POST` (default) methods in webhook notification provider as well as use [notification template variables](http://www.appveyor.com/docs/notifications#customizing-message-template) in header values and URL, for example:

```
- provider: Webhook
  url: http://requestb.in/test?appveyor_build_version={{build.BuildVersion}}&appveyor_commit_id={{build.CommitId}}
  method: GET
  headers:
    APPVEYOR-PROJECT-NAME: '{{build.ProjectName}}'
    APPVEYOR-BUILD-VERSION: '{{build.BuildVersion}}'
    APPVEYOR-COMMIT-ID: '{{build.CommitId}}'
```

Requested by Octavian Cosma
