### ISSUE TITLE
Azure Storage Emulator 4.3

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#796]
There's a new version of the azure storage emulator which is v4.3.

I just updated my [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/7.0.0) NuGet package to `7.0.0` and now my unit tests are failing.

The recommendation from someone at Microsoft is to use the newest storage emulator. https://github.com/Azure/azure-webjobs-sdk/issues/718

The download link can be found at https://azure.microsoft.com/en-us/downloads/ and is https://download.microsoft.com/download/B/4/A/B4A8422F-C564-4393-80DA-6865A8C4B32D/MicrosoftAzureStorageEmulator.msi

**Comment by xt0rted** [comment]
Manually installing as per #445 results in my tests passing again.

**Comment by FeodorFitsner** [comment]
That's strange as "VS 2015" image has 4.3 installed already. What's URL of your project? What build worker image do you use?

**Comment by xt0rted** [comment]
The project url is `xt0rted/eei`. I'm not explicitly setting a build worker image. Based on the settings UI isn't this vs2015 by default?

**Comment by FeodorFitsner** [comment]
Yes, it should be VS 2015 by default.

I'm looking at the list of installed software and there is v4.3 installed (4.3.6891.5 to be specific):

![image](https://cloud.githubusercontent.com/assets/5041459/15131301/a2ba5e7a-1603-11e6-9772-4502a7b9604c.png)

**Comment by xt0rted** [comment]
These are the two builds I'm working against.
https://ci.appveyor.com/project/xt0rted/eei/build/80
https://ci.appveyor.com/project/xt0rted/eei/build/81

The only difference between them was adding this to my install scripts.
```yaml
- ps: |
    $msiPath = "$($env:USERPROFILE)\MicrosoftAzureStorageEmulator.msi"
    (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/B/4/A/B4A8422F-C564-4393-80DA-6865A8C4B32D/MicrosoftAzureStorageEmulator.msi', $msiPath)
    cmd /c start /wait msiexec /i $msiPath /quiet
```

**Comment by FeodorFitsner** [comment]
That's weird indeed. Look at this build - I'm checking emulator version before and after running the installer: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.2124

Maybe it just needed re-installing? What error were you getting?

**Comment by FeodorFitsner** [comment]
Even a better check: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.2128

[In that report](https://github.com/Azure/azure-webjobs-sdk/issues/718#issue-153858988) your logs are saying:

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
Windows Azure Storage Emulator 4.2.0.0 command line tool
The storage emulator was successfully started.
```

in my test I'm calling it from the same location.

You are not using `Previous Visual Studio 2015` image, aren't you?

**Comment by xt0rted** [comment]
Is there a way to check during the build what worker image is being used?

This is a stripped down version of my `appveyor.yml`

```yaml
branches:
  only:
    - master

version: '{build}'

assembly_info:
  patch: true

configuration: Release

environment:
  nodejs_version: "5.7.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: |
      $msiPath = "$($env:USERPROFILE)\MicrosoftAzureStorageEmulator.msi"
      (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/B/4/A/B4A8422F-C564-4393-80DA-6865A8C4B32D/MicrosoftAzureStorageEmulator.msi', $msiPath)
      cmd /c start /wait msiexec /i $msiPath /quiet
  - cmd: |
      "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
      "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" status

before_build:
  - ps: nuget restore -configfile ".nuget\NuGet.config"

build:
  parallel: true

on_finish:
  - cmd: |
      "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" stop

notifications:
  - provider: Slack
```
